In [1]:
from nba_api.stats.endpoints import leaguegamelog, gamerotation, playbyplayv3
import pandas as pd
import numpy as np
from tqdm import tqdm
import time

In [2]:
# from nba_api.stats.static import teams

# nba_teams = teams.get_teams()
# # Select the dictionary for the Celtics, which contains their team ID
# celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
# celtics_id = celtics['id']

# Get Games in a Season

In [4]:
# from nba_api.stats.endpoints import leaguegamefinder

# # Query for games where the Celtics were playing
# gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# # The first DataFrame of those returned is what we want.
# games = gamefinder.get_data_frames()[0]
# games.head()

In [5]:
games_df = leaguegamelog.LeagueGameLog(player_or_team_abbreviation = 'T', season = '2023-24', season_type_all_star = 'Regular Season').get_data_frames()[0]
games_df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,48,...,33,42,29,9,6,12,15,119,12,1
1,22023,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,36,...,31,49,19,11,6,11,23,104,-4,1
2,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,31,44,23,5,4,12,18,107,-12,1
3,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,...,43,60,23,5,7,19,22,108,4,1
4,22023,1610612737,ATL,Atlanta Hawks,0022300063,2023-10-25,ATL @ CHA,L,240,39,...,30,42,24,12,1,12,19,110,-6,1

# Get Rotation for a Given Game

In [7]:
ht_rotation = gamerotation.GameRotation(game_id = games_df.GAME_ID[0]).get_data_frames()[1]
ht_rotation['home_away_flg'] = 'H'
at_rotation = gamerotation.GameRotation(game_id = games_df.GAME_ID[0]).get_data_frames()[0]
at_rotation['home_away_flg'] = 'A'
rotation_df = pd.concat([ht_rotation, at_rotation])
rotation_df.head()

,GAME_ID,TEAM_ID,TEAM_CITY,TEAM_NAME,PERSON_ID,PLAYER_FIRST,PLAYER_LAST,IN_TIME_REAL,OUT_TIME_REAL,PLAYER_PTS,PT_DIFF,USG_PCT,home_away_flg
0,0022300061,1610612743,Denver,Nuggets,202704,Reggie,Jackson,3530.0,8890.0,8,14.0,0.278,H
1,0022300061,1610612743,Denver,Nuggets,202704,Reggie,Jackson,9220.0,11940.0,0,-4.0,0.273,H
2,0022300061,1610612743,Denver,Nuggets,202704,Reggie,Jackson,18510.0,24870.0,0,1.0,0.095,H
3,0022300061,1610612743,Denver,Nuggets,203484,Kentavious,Caldwell-Pope,0.0,5500.0,5,11.0,0.174,H
4,0022300061,1610612743,Denver,Nuggets,203484,Kentavious,Caldwell-Pope,8890.0,20620.0,11,-6.0,0.204,H

In [8]:
rotation_df = rotation_df.sort_values(by = ['IN_TIME_REAL', 'OUT_TIME_REAL'], ascending = [True, True])
rotation_df = rotation_df.reset_index(drop = True)
rotation_df['IN_TIME_REAL'] = np.ceil(rotation_df['IN_TIME_REAL']/10) #Divide by 10 to get actual seconds
rotation_df['OUT_TIME_REAL'] = np.ceil(rotation_df['OUT_TIME_REAL']/10) #Divide by 10 to get actual seconds
rotation_df.head()

,GAME_ID,TEAM_ID,TEAM_CITY,TEAM_NAME,PERSON_ID,PLAYER_FIRST,PLAYER_LAST,IN_TIME_REAL,OUT_TIME_REAL,PLAYER_PTS,PT_DIFF,USG_PCT,home_away_flg
0,0022300061,1610612743,Denver,Nuggets,1627750,Jamal,Murray,0.0,353.0,5,4.0,0.267,H
1,0022300061,1610612747,L.A. Lakers,Lakers,2544,LeBron,James,0.0,353.0,4,-4.0,0.200,A
2,0022300061,1610612747,L.A. Lakers,Lakers,1626156,D'Angelo,Russell,0.0,353.0,0,-4.0,0.200,A
3,0022300061,1610612743,Denver,Nuggets,203484,Kentavious,Caldwell-Pope,0.0,550.0,5,11.0,0.174,H
4,0022300061,1610612743,Denver,Nuggets,203932,Aaron,Gordon,0.0,550.0,2,11.0,0.043,H

# Get PBP Stats for a Given Game

In [10]:
pbp = playbyplayv3.PlayByPlayV3(game_id = games_df.GAME_ID[0]).get_data_frames()[0]
pbp.head()

,gameId,actionNumber,clock,period,teamId,teamTricode,personId,playerName,playerNameI,xLegacy,...,scoreHome,scoreAway,pointsTotal,location,description,actionType,subType,videoAvailable,shotValue,actionId
0,0022300061,2,PT12M00.00S,1,0,,0,,,0,...,0,0,0,,Start of 1st Period (7:36 PM EST),period,start,0,0,1
1,0022300061,4,PT12M00.00S,1,1610612743,DEN,203999,Jokić,N. Jokić,0,...,,,0,h,Jump Ball Jokic vs. Davis: Tip to James,Jump Ball,,1,0,2
2,0022300061,7,PT11M42.00S,1,1610612747,LAL,203076,Davis,A. Davis,2,...,0,2,2,v,Davis 1' Dunk (2 PTS) (Russell 1 AST),Made Shot,Dunk Shot,1,2,3
3,0022300061,10,PT11M15.00S,1,1610612743,DEN,203999,Jokić,N. Jokić,13,...,2,2,4,h,Jokic 7' Driving Floating Jump Shot (2 PTS) (M...,Made Shot,Driving Floating Jump Shot,1,2,4
4,0022300061,11,PT10M57.00S,1,1610612747,LAL,1627752,Prince,T. Prince,237,...,2,5,7,v,Prince 24' 3PT Jump Shot (3 PTS) (James 1 AST),Made Shot,Jump Shot,1,3,5

## Calculate Game Breakpoints

In [12]:
breakpoints = sorted(set(rotation_df['IN_TIME_REAL']).union(set(rotation_df['OUT_TIME_REAL'])))
breakpoints

[0.0,
 353.0,
 550.0,
 680.0,
 720.0,
 889.0,
 898.0,
 922.0,
 1015.0,
 1045.0,
 1194.0,
 1313.0,
 1440.0,
 1756.0,
 1851.0,
 1868.0,
 1925.0,
 2062.0,
 2160.0,
 2351.0,
 2352.0,
 2385.0,
 2474.0,
 2487.0,
 2516.0,
 2805.0,
 2837.0,
 2880.0]

In [13]:
len(breakpoints)

28

## Calculate Stints and Point Differential

In [15]:
#Get Actual Point Differential
pbp['time_completed'] = ((pbp['period']-1) * 12*60) + ((12*60) - pbp['clock'].str[2:4].astype(float)*60 - pbp['clock'].str[5:7].astype(float))
pbp_formatted = pbp[['clock', 'time_completed', 'scoreHome', 'scoreAway', 'description', 'actionType']].copy()
pbp_formatted['scoreHome'].replace('', np.nan, inplace = True)
pbp_formatted['scoreAway'].replace('', np.nan, inplace = True)
pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)

pbp_formatted['scoreHome'] = pbp_formatted['scoreHome'].astype(int)
pbp_formatted['scoreAway'] = pbp_formatted['scoreAway'].astype(int)




pbp_formatted['STINT_START_TIME'] = pbp_formatted['time_completed'].shift(1)
pbp_formatted['STINT_START_TIME'] = pbp_formatted['STINT_START_TIME'].fillna(0)

pbp_formatted.rename(columns = {'time_completed': 'STINT_END_TIME'}, inplace = True)
pbp_formatted = pbp_formatted.loc[pbp_formatted['STINT_END_TIME'].isin(breakpoints)]


pt_diff_df = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])

for i in range(len(breakpoints) - 1):
    t = breakpoints[i]
    t_plus_1 = breakpoints[i+1]

    temp = pbp_formatted.loc[(pbp_formatted['STINT_START_TIME'] >= t) & (pbp_formatted['STINT_END_TIME'] <= t_plus_1)]
    res = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])

    res.loc[0, 'STINT_START_TIME'] = t 
    res.loc[0, 'STINT_END_TIME'] = t_plus_1

    diff = 0

    if t == 0:
        diff = np.max(temp['scoreHome']) - np.max(temp['scoreAway'])
    
    else:
        end_home_score = temp.loc[(temp['STINT_END_TIME'] == t_plus_1) & (temp['actionType'].isin(['Substitution', 'period']))]['scoreHome'].values[0]
        end_away_score = temp.loc[(temp['STINT_END_TIME'] == t_plus_1) & (temp['actionType'].isin(['Substitution', 'period']))]['scoreAway'].values[0]
        # diff = (np.max(temp['scoreHome']) - np.min(temp['scoreHome'])) - (np.max(temp['scoreAway']) - np.min(temp['scoreAway']))
        diff = (end_home_score - np.min(temp['scoreHome'])) - (end_away_score - np.min(temp['scoreAway']))
    
    res.loc[0, 'PT_DIFF'] = diff 

    pt_diff_df = pd.concat([pt_diff_df, res], axis = 0)
    pt_diff_df = pt_diff_df.reset_index(drop = True)

pt_diff_df

/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/139070337.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)

   STINT_START_TIME STINT_END_TIME PT_DIFF
0               0.0          353.0       4
1             353.0          550.0       7
2             550.0          680.0      -1
3             680.0          720.0       4
4             720.0          889.0       4
5             889.0          898.0       0
6             898.0          922.0      -2
7             922.0         1015.0      -4
8            1015.0         1045.0       1
9            1045.0         1194.0       0
10           1194.0         1313.0      -1
11           1313.0         1440.0      -3
12           1440.0         1756.0      -1
13           1756.0         1851.0       1
14           1851.0         1868.0       2
15           1868.0         1925.0       0
16           1925.0         2062.0       1
17           2062.0         2160.0      -5
18           2160.0         2351.0      -3
19           2351.0         2352.0       0
20           2352.0         2385.0       3
21           2385.0         2474.0       4
22           2474.0         2487.0       0
23           2487.0         2516.0       1
24           2516.0         2805.0       0
25           2805.0         2837.0       0
26           2837.0         2880.0       0

# Get In-Time and Out-Time for each Player

In [17]:
players = list(set(rotation_df.PERSON_ID))
# players = ['PERSON_ID_'+str(i) for i in players]
players

[1629060,
 1631108,
 1631128,
 203932,
 1629216,
 1626156,
 1629618,
 1629629,
 1626174,
 203076,
 1629637,
 1629008,
 202704,
 1630296,
 203484,
 1630559,
 203999,
 1627750,
 1627752,
 1631212,
 2544,
 1630192,
 1631221,
 1641721]

In [18]:
player_id_cols = ['PERSON_ID_'+str(p) for p in players]
player_flags_df = pd.get_dummies(rotation_df, columns = ['PERSON_ID'], dtype = int).copy()
player_flags_df = player_flags_df.groupby(['IN_TIME_REAL', 'OUT_TIME_REAL'])[player_id_cols].sum().reset_index()
player_flags_df

,IN_TIME_REAL,OUT_TIME_REAL,PERSON_ID_1629060,PERSON_ID_1631108,PERSON_ID_1631128,PERSON_ID_203932,PERSON_ID_1629216,PERSON_ID_1626156,PERSON_ID_1629618,PERSON_ID_1629629,...,PERSON_ID_203484,PERSON_ID_1630559,PERSON_ID_203999,PERSON_ID_1627750,PERSON_ID_1627752,PERSON_ID_1631212,PERSON_ID_2544,PERSON_ID_1630192,PERSON_ID_1631221,PERSON_ID_1641721
0,0.0,353.0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
1,0.0,550.0,0,0,0,1,0,0,0,0,...,1,1,1,0,1,0,0,0,0,0
2,353.0,680.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,353.0,889.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,353.0,898.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,550.0,720.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,550.0,889.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,550.0,922.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
8,550.0,1015.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,550.0,1045.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,680.0,1045.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,720.0,1194.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,889.0,1313.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,889.0,2062.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
14,898.0,1194.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,922.0,1194.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,922.0,1925.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,922.0,2062.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,1015.0,1925.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19,1045.0,1851.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,1045.0,1868.0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
21,1194.0,1440.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1194.0,1756.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1194.0,1851.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
24,1313.0,1756.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
25,1440.0,2062.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1756.0,2062.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1756.0,2474.0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,1851.0,2487.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1851.0,2516.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,1868.0,2385.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
31,1925.0,2160.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32,1925.0,2385.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2062.0,2351.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
34,2062.0,2352.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
35,2062.0,2385.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
36,2062.0,2516.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,2160.0,2385.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,2351.0,2837.0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
39,2352.0,2805.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,2385.0,2805.0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
41,2385.0,2837.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
42,2474.0,2805.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
43,2487.0,2837.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
44,2516.0,2805.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
45,2516.0,2837.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,2805.0,2880.0,0,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
47,2837.0,2880.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,1,0

# Final Stint-wise Point Differential DataFrame

In [20]:
final_stints_df = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME'] + players + ['PT_DIFF'])

for i in tqdm(range(len(breakpoints) - 1)):
  t = breakpoints[i]
  t_plus_1 = breakpoints[i+1]
  stint_players = rotation_df.loc[(rotation_df['IN_TIME_REAL'] <= t) & (rotation_df['OUT_TIME_REAL'] > t)][['PERSON_ID']].values.flatten().tolist()
  home_away_flgs = rotation_df.loc[(rotation_df['IN_TIME_REAL'] <= t) & (rotation_df['OUT_TIME_REAL'] > t)][['home_away_flg']].values.tolist()
  # pt_diff = stints_df.loc[(stints_df['STINT_START_TIME_FIXED'] == t) & (stints_df['STINT_END_TIME'] == t_plus_1)]['PT_DIFF'].sum()
  pt_diff = pt_diff_df.loc[(pt_diff_df['STINT_START_TIME'] == t) & (pt_diff_df['STINT_END_TIME'] == t_plus_1)]['PT_DIFF'].values[0]

  X = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME'] + players + ['PT_DIFF'])
  X.loc[0, 'STINT_START_TIME'] = t
  X.loc[0, 'STINT_END_TIME'] = t_plus_1
  X.loc[0, 'PT_DIFF'] = pt_diff

  for player in players:
    if player in stint_players:
      if home_away_flgs[stint_players.index(player)] == 'H':
        X.loc[0, player] = 1
      else:
        X.loc[0, player] = -1
    else:
      X.loc[0, player] = 0

  final_stints_df = pd.concat([final_stints_df, X], axis = 0)

final_stints_df = final_stints_df.reset_index(drop = True)
final_stints_df

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 674.00it/s]

,STINT_START_TIME,STINT_END_TIME,1629060,1631108,1631128,203932,1629216,1626156,1629618,1629629,...,1630559,203999,1627750,1627752,1631212,2544,1630192,1631221,1641721,PT_DIFF
0,0.0,353.0,0,0,0,-1,0,-1,0,0,...,-1,-1,-1,-1,0,-1,0,0,0,4
1,353.0,550.0,-1,0,0,-1,-1,0,0,0,...,-1,-1,0,-1,0,0,0,0,0,7
2,550.0,680.0,-1,0,-1,0,-1,-1,0,-1,...,0,0,-1,0,-1,0,-1,0,0,-1
3,680.0,720.0,0,0,-1,0,-1,-1,0,-1,...,0,0,-1,0,-1,-1,-1,0,0,4
4,720.0,889.0,0,0,-1,0,-1,-1,0,0,...,0,0,-1,0,-1,-1,-1,0,0,4
5,889.0,898.0,0,0,-1,0,-1,-1,0,0,...,0,0,-1,0,-1,-1,-1,0,0,0
6,898.0,922.0,0,0,-1,0,0,-1,0,-1,...,0,0,-1,0,-1,-1,-1,0,0,-2
7,922.0,1015.0,0,0,-1,-1,0,-1,0,-1,...,0,-1,0,0,0,-1,0,0,0,-4
8,1015.0,1045.0,0,0,-1,-1,0,0,0,-1,...,-1,-1,0,0,0,-1,0,0,0,1
9,1045.0,1194.0,0,0,0,-1,0,0,0,-1,...,-1,-1,0,-1,0,0,0,0,0,0
10,1194.0,1313.0,-1,0,0,-1,0,-1,0,0,...,-1,-1,-1,-1,0,0,0,0,0,-1
11,1313.0,1440.0,-1,0,0,-1,0,-1,0,0,...,-1,-1,-1,-1,0,-1,0,0,0,-3
12,1440.0,1756.0,0,0,0,-1,0,-1,0,0,...,-1,-1,-1,-1,0,-1,0,0,0,-1
13,1756.0,1851.0,-1,0,0,-1,-1,0,0,0,...,-1,-1,-1,-1,0,0,0,0,0,1
14,1851.0,1868.0,-1,0,-1,-1,-1,0,0,0,...,-1,-1,0,-1,0,0,0,0,0,2
15,1868.0,1925.0,-1,0,-1,-1,-1,0,0,-1,...,-1,-1,0,0,0,0,0,0,0,0
16,1925.0,2062.0,-1,0,-1,0,-1,-1,0,-1,...,0,-1,0,0,-1,0,0,0,0,1
17,2062.0,2160.0,0,0,-1,0,-1,-1,0,-1,...,0,0,-1,0,-1,-1,-1,0,0,-5
18,2160.0,2351.0,0,0,-1,-1,-1,-1,0,-1,...,0,0,-1,0,0,-1,-1,0,0,-3
19,2351.0,2352.0,0,0,-1,-1,-1,-1,0,-1,...,0,-1,-1,0,0,-1,0,0,0,0
20,2352.0,2385.0,0,0,-1,-1,-1,-1,0,-1,...,0,-1,-1,0,0,0,0,0,0,3
21,2385.0,2474.0,0,0,-1,0,-1,0,0,0,...,-1,-1,0,-1,0,0,0,0,0,4
22,2474.0,2487.0,0,0,-1,0,0,-1,0,0,...,-1,-1,0,-1,0,0,0,0,0,0
23,2487.0,2516.0,0,0,-1,0,0,-1,0,0,...,-1,-1,-1,-1,0,0,0,0,0,1
24,2516.0,2805.0,0,0,0,-1,0,-1,0,0,...,-1,-1,-1,-1,0,-1,0,0,0,0
25,2805.0,2837.0,0,-1,0,-1,-1,0,0,-1,...,0,-1,-1,0,0,0,0,0,-1,0
26,2837.0,2880.0,0,-1,0,0,-1,0,-1,-1,...,0,0,0,0,-1,0,-1,-1,-1,0

In [21]:
np.sum(final_stints_df['PT_DIFF'])

12

# Scraping Definition

## GameLog to GameID

In [24]:
def gamelog_gameid(szn:str):
    X = leaguegamelog.LeagueGameLog(player_or_team_abbreviation = 'T', season = szn, season_type_all_star = 'Regular Season').get_data_frames()[0]
    return X, set(X['GAME_ID'])

In [25]:
gamelog_gameid('2024-25')

(     SEASON_ID     TEAM_ID TEAM_ABBREVIATION               TEAM_NAME  \
 0        22024  1610612738               BOS          Boston Celtics
 1        22024  1610612747               LAL      Los Angeles Lakers
 2        22024  1610612750               MIN  Minnesota Timberwolves
 3        22024  1610612752               NYK         New York Knicks
 4        22024  1610612737               ATL           Atlanta Hawks
 ...        ...         ...               ...                     ...
 2455     22024  1610612762               UTA               Utah Jazz
 2456     22024  1610612763               MEM       Memphis Grizzlies
 2457     22024  1610612764               WAS      Washington Wizards
 2458     22024  1610612765               DET         Detroit Pistons
 2459     22024  1610612766               CHA       Charlotte Hornets

          GAME_ID   GAME_DATE      MATCHUP WL  MIN  FGM  ...  DREB  REB  AST  \
 0     0022400061  2024-10-22  BOS vs. NYK  W  240   48  ...    29   40   33
 1     0022400062  2024-10-22  LAL vs. MIN  W  240   42  ...    31   46   22
 2     0022400062  2024-10-22    MIN @ LAL  L  240   35  ...    35   47   17
 3     0022400061  2024-10-22    NYK @ BOS  L  240   43  ...    29   34   20
 4     0022400064  2024-10-23  ATL vs. BKN  W  240   39  ...    33   45   25
 ...          ...         ...          ... ..  ...  ...  ...   ...  ...  ...
 2455  0022401195  2025-04-13    UTA @ MIN  L  240   40  ...    31   40   24
 2456  0022401194  2025-04-13  MEM vs. DAL  W  240   52  ...    34   53   31
 2457  0022401190  2025-04-13    WAS @ MIA  W  240   46  ...    37   43   33
 2458  0022401192  2025-04-13    DET @ MIL  L  265   51  ...    28   42   35
 2459  0022401187  2025-04-13    CHA @ BOS  L  240   32  ...    33   51   23

       STL  BLK  TOV  PF  PTS  PLUS_MINUS  VIDEO_AVAILABLE
 0       6    3    4  15  132          23                1
 1       7    8    7  22  110           7                1
 2       4    1   16  22  103          -7                1
 3       2    3   12  12  109         -23                1
 4      12    9   16  20  120           4                1
 ...   ...  ...  ...  ..  ...         ...              ...
 2455    6    5   14  15  105         -11                1
 2456   13    7   12  15  132          35                1
 2457    4    3   11  14  119           1                1
 2458    9    3   13  19  133          -7                1
 2459   10    4   17  16   86          -7                1

 [2460 rows x 29 columns],
 {'0022400221',
  '0022400084',
  '0022400263',
  '0022400618',
  '0022400272',
  '0022400750',
  '0022400340',
  '0022400114',
  '0022400403',
  '0022400234',
  '0022400346',
  '0022400235',
  '0022401061',
  '0022400519',
  '0022400670',
  '0022400702',
  '0022400226',
  '0022400277',
  '0022401075',
  '0022400775',
  '0022400754',
  '0022400609',
  '0022400599',
  '0022400746',
  '0022400892',
  '0022401140',
  '0022400725',
  '0022400798',
  '0022400348',
  '0022400125',
  '0022400139',
  '0022400495',
  '0022401167',
  '0022400829',
  '0022400800',
  '0022400652',
  '0022400106',
  '0022400090',
  '0022401149',
  '0022400023',
  '0022400873',
  '0022400824',
  '0022401109',
  '0022400101',
  '0022400503',
  '0022400371',
  '0022401190',
  '0022400222',
  '0022400927',
  '0022400991',
  '0022400597',
  '0022400575',
  '0022400062',
  '0022400836',
  '0022400799',
  '0022400296',
  '0022400550',
  '0022400209',
  '0022401152',
  '0022400241',
  '0022400075',
  '0022400719',
  '0022400554',
  '0022401087',
  '0022401106',
  '0022400435',
  '0022401148',
  '0022400338',
  '0022400300',
  '0022401005',
  '0022400157',
  '0022400788',
  '0022400050',
  '0022400342',
  '0022400421',
  '0022400580',
  '0022400344',
  '0022400498',
  '0022400774',
  '0022400237',
  '0022400738',
  '0022400720',
  '0022401187',
  '0022400529',
  '0022401096',
  '0022400291',
  '0022400463',
  '0022400996',
  '0022401055',
  '0022400791',
  '0022400462',
  '0022400169',
  '0022400659',
  '0022400535',
  '0022400129',
  '0022401044',
  '0022400780',
  '0022400565',
  '0022400482',
  '0022401089',
  '0022400849',
  '0022400944',
  '0022400264',
  '0022400361',
  '0022400271',
  '0022400322',
  '0022400392',
  '0022400636',
  '0022400028',
  '0022400592',
  '0022400552',
  '0022400832',
  '0022400814',
  '0022400997',
  '0022400629',
  '0022400189',
  '0022401059',
  '0022400729',
  '0022400921',
  '0022400413',
  '0022400803',
  '0022401095',
  '0022400896',
  '0022401022',
  '0022401083',
  '0022400424',
  '0022400596',
  '0022401192',
  '0022400286',
  '0022400243',
  '0022400982',
  '0022400242',
  '0022400654',
  '0022401102',
  '0022401156',
  '0022400038',
  '0022401195',
  '0022400658',
  '0022400416',
  '0022401058',
  '0022400072',
  '0022400076',
  '0022400877',
  '0022401098',
  '0022400761',
  '0022401091',
  '0022400656',
  '0022401088',
  '0022400236',
  '0022400120',
  '0022400906',
  '0022400203',
  '0022400224',
  '0022401060',
  '0022401197',
  '0022400326',
  '0022400841',
  '0022401129',
  '0022400981',
  '0022401050',
  '0022400638',
  '0022400204',
  '0022401086',
  '0022401097',
  '0022401114',
  '0022400088',
  '0022400566',
  '0022400395',
  '0022400847',
  '0022400582',
  '0022400092',
  '0022401008',
  '0022401013',
  '0022400018',
  '0022400807',
  '0022400804',
  '0022401212',
  '0022400011',
  '0022400953',
  '0022400848',
  '0022400794',
  '0022400556',
  '0022400930',
  '0022400183',
  '0022400451',
  '0022400570',
  '0022400105',
  '0022401070',
  '0022401033',
  '0022400274',
  '0022400769',
  '0022400913',
  '0022400928',
  '0022401226',
  '0022400806',
  '0022400752',
  '0022400394',
  '0022400851',
  '0022400248',
  '0022400813',
  '0022400486',
  '0022400014',
  '0022400328',
  '0022400015',
  '0022400060',
  '0022400147',
  '0022400653',
  '0022400282',
  '0022400453',
  '0022400909',
  '0022400141',
  '0022400083',
  '0022400938',
  '0022401043',
  '0022400667',
  '0022400971',
  '0022400999',
  '0022400943',
  '0022400977',
  '0022400904',
  '0022400850',
  '0022400070',
  '0022401047',
  '0022400331',
  '0022400194',
  '0022401154',
  '0022400671',
  '0022401010',
  '0022401163',
  '0022401222',
  '0022400478',
  '0022400889',
  '0022400161',
  '0022400908',
  '0022400042',
  '0022400644',
  '0022400460',
  '0022400585',
  '0022400715',
  '0022400207',
  '0022400781',
  '0022400965',
  '0022400218',
  '0022400619',
  '0022400741',
  '0022400669',
  '0022400680',
  '0022401099',
  '0022400383',
  '0022400370',
  '0022400732',
  '0022400864',
  '0022401081',
  '0022401171',
  '0022401084',
  '0022400578',
  '0022400593',
  '0022401225',
  '0022400240',
  '0022400862',
  '0022400468',
  '0022400762',
  '0022400199',
  '0022401150',
  '0022400283',
  '0022400925',
  '0022400068',
  '0022400700',
  '0022401221',
  '0022400012',
  '0022400546',
  '0022400689',
  '0022400883',
  '0022400381',
  '0022400065',
  '0022400419',
  '0022400527',
  '0022400547',
  '0022400933',
  '0022400107',
  '0022400639',
  '0022400607',
  '0022401201',
  '0022400721',
  '0022400091',
  '0022400021',
  '0022400591',
  '0022400707',
  '0022400748',
  '0022401131',
  '0022400115',
  '0022400439',
  '0022400045',
  '0022400586',
  '0022400164',
  '0022401057',
  '0022401018',
  '0022401143',
  '0022400513',
  '0022400590',
  '0022400418',
  '0022400990',
  '0022400627',
  '0022400989',
  '0022400446',
  '0022400751',
  '0022400515',
  '0022400461',
  '0022400542',
  '0022400459',
  '0022400229',
  '0022400399',
  '0022401073',
  '0022401142',
  '0022400544',
  '0022400389',
  '0022400972',
  '0022401035',
  '0022401227',
  '0022400039',
  '0022400053',
  '0022400201',
  '0022401066',
  '0022400401',
  '0022400853',
  '0022401015',
  '0022400131',
  '0022400153',
  '0022400540',
  '0022400258',
  '0022400998',
  '0022400245',
  '0022400499',
  '0022400173',
  '0022400912',
  '0022400826',
  '0022400002',
  '0022400345',
  '0022401014',
  '0022400128',
  '0022401162',
  '0022401069',
  '0022400683',
  '0022401020',
  '0022401194',
  '0022400894',
  '0022400507',
  '0022400190',
  '0022400936',
  '0022401144',
  '0022400182',
  '0022400265',
  '0022400089',
  '0022400410',
  '0022400801',
  '0022401139',
  '0022400198',
  '0022401160',
  '0022400710',
  '0022400931',
  '0022400415',
  '0022401141',
  '0022400195',
  '0022401062',
  '0022400867',
  '0022400156',
  '0022400162',
  '0022400595',
  '0022400549',
  '0022400726',
  '0022400782',
  '0022401132',
  '0022400678',
  '0022400078',
  '0022400473',
  '0022400844',
  '0022401113',
  '0022400811',
  '0022400281',
  '0022400500',
  '0022400375',
  '0022401215',
  '0022401207',
  '0022400058',
  '0022400431',
  '0022400151',
  '0022400108',
  '0022401165',
  '0022401009',
  '0022400049',
  '0022400979',
  '0022400146',
  '0022400422',
  '0022400902',
  '0022400555',
  '0022400820',
  '0022400351',
  '0022400966',
  '0022400197',
  '0022400886',
  '0022401224',
  '0022401004',
  '0022400970',
  '0022400343',
  '0022400316',
  '0022400487',
  '0022400651',
  '0022401072',
  '0022401137',
  '0022400866',
  '0022400335',
  '0022400793',
  '0022400668',
  '0022401119',
  '0022400745',
  '0022400693',
  '0022401064',
  '0022401037',
  '0022400337',
  '0022400411',
  '0022400805',
  '0022400116',
  '0022401120',
  '0022400425',
  '0022400052',
  '0022400254',
  '0022400041',
  '0022400481',
  '0022400647',
  '0022400225',
  '0022400576',
  '0022401214',
  '0022400417',
  '0022400350',
  '0022401173',
  '0022401185',
  '0022400622',
  '0022400737',
  '0022401145',
  '0022400899',
  '0022400033',
  '0022400219',
  '0022400692',
  '0022400145',
  '0022401178',
  '0022400917',
  '0022400882',
  '0022400512',
  '0022400932',
  '0022400206',
  '0022400407',
  '0022400010',
  '0022401101',
  '0022400543',
  '0022400475',
  '0022400321',
  '0022400860',
  '0022400016',
  '0022400155',
  '0022400441',
  '0022400436',
  '0022400093',
  '0022400457',
  '0022400776',
  '0022400975',
  '0022401220',
  '0022400608',
  '0022401071',
  '0022400879',
  '0022401117',
  '0022401191',
  '0022400937',
  '0022400352',
  '0022400297',
  '0022400884',
  '0022400284',
  '0022401202',
  '0022400123',
  '0022400579',
  '0022400534',
  '0022400136',
  '0022400916',
  '0022400623',
  '0022400974',
  '0022401027',
  '0022400766',
  '0022400733',
  '0022401158',
  '0022400524',
  '0022400987',
  '0022400771',
  '0022400888',
  '0022400734',
  '0022400110',
  '0022400797',
  '0022400594',
  '0022400765',
  '0022401122',
  '0022400713',
  '0022400304',
  '0022400983',
  '0022400643',
  '0022401112',
  '0022400910',
  '0022401174',
  '0022400792',
  '0022400454',
  '0022400964',
  '0022401019',
  '0022400388',
  '0022400548',
  '0022400951',
  '0022400787',
  '0022400589',
  '0022400102',
  '0022400830',
  '0022400655',
  '0022400210',
  '0022400013',
  '0022400347',
  '0022400484',
  '0022400602',
  '0022401124',
  '0022400324',
  '0022401051',
  '0022400275',
  '0022400220',
  '0022400819',
  '0022400985',
  '0022400024',
  '0022400822',
  '0022401025',
  '0022400471',
  '0022401082',
  '0022400290',
  '0022401155',
  '0022400025',
  '0022400193',
  '0022400757',
  '0022401078',
  '0022400212',
  '0022400510',
  '0022400192',
  '0022401136',
  '0022400759',
  '0022401205',
  '0022400067',
  '0022400790',
  '0022400558',
  '0022400387',
  '0022400465',
  '0022400148',
  '0022400663',
  '0022401054',
  '0022400073',
  '0022400276',
  '0022401218',
  '0022400363',
  '0022400517',
  '0022400828',
  '0022400132',
  '0022400119',
  '0022400679',
  '0022400488',
  '0022400165',
  '0022400289',
  '0022400312',
  '0022400613',
  '0022400391',
  '0022400440',
  '0022400035',
  '0022400009',
  '0022401030',
  '0022400299',
  '0022400980',
  '0022400995',
  '0022400577',
  '0022401045',
  '0022401130',
  '0022400968',
  '0022400684',
  '0022401111',
  '0022400056',
  '0022400167',
  '0022400097',
  '0022400205',
  '0022400664',
  '0022400497',
  '0022400587',
  '0022400695',
  '0022400920',
  '0022400429',
  '0022400104',
  '0022400557',
  '0022400071',
  '0022400942',
  '0022400961',
  '0022400257',
  '0022401046',
  '0022400452',
  '0022401126',
  '0022400840',
  '0022400876',
  '0022400133',
  '0022400442',
  '0022400753',
  '0022400818',
  '0022400941',
  '0022400949',
  '0022400449',
  '0022400314',
  '0022401206',
  '0022401182',
  '0022400903',
  '0022400279',
  '0022400244',
  '0022400261',
  '0022400887',
  '0022400825',
  '0022400962',
  '0022400170',
  '0022400528',
  '0022401151',
  '0022401176',
  '0022400302',
  '0022400168',
  '0022400810',
  '0022400516',
  '0022400779',
  '0022401079',
  '0022400492',
  '0022401133',
  '0022400605',
  '0022401041',
  '0022400187',
  '0022401093',
  '0022400188',
  '0022400705',
  '0022401076',
  '0022401121',
  '0022400874',
  '0022400539',
  '0022400085',
  '0022400313',
  '0022400502',
  '0022400634',
  '0022400149',
  '0022400309',
  '0022401159',
  '0022400907',
  '0022400521',
  '0022400385',
  '0022400967',
  '0022400096',
  '0022400532',
  '0022400784',
  '0022401067',
  '0022400166',
  '0022400008',
  '0022400356',
  '0022401080',
  '0022400428',
  '0022400384',
  '0022401181',
  '0022400217',
  '0022400306',
  '0022401204',
  '0022400480',
  '0022400064',
  '0022400017',
  '0022401017',
  '0022400406',
  '0022400615',
  '0022400898',
  '0022400863',
  '0022400694',
  '0022400861',
  '0022401029',
  '0022400960',
  '0022400890',
  '0022400081',
  '0022400880',
  '0022400574',
  '0022400095',
  '0022400505',
  '0022400537',
  '0022401021',
  '0022400450',
  '0022400177',
  '0022401034',
  '0022400171',
  '0022400367',
  '0022400994',
  '0022400174',
  '0022400742',
  '0022400839',
  '0022401039',
  '0022400007',
  '0022400144',
  '0022400360',
  '0022400270',
  '0022400777',
  '0022401146',
  '0022400288',
  '0022401164',
  '0022400259',
  '0022400255',
  '0022400650',
  '0022401090',
  '0022400310',
  '0022400396',
  '0022400458',
  '0022400572',
  '0022401038',
  '0022400005',
  '0022400474',
  '0022400004',
  '0022400564',
  '0022400562',
  '0022400437',
  '0022400365',
  '0022400992',
  '0022400993',
  '0022400112',
  '0022400897',
  '0022400231',
  '0022400986',
  '0022401203',
  '0022400666',
  '0022400358',
  '0022401052',
  '0022400739',
  '0022400124',
  '0022400657',
  '0022400376',
  '0022401011',
  '0022400176',
  '0022400373',
  '0022400940',
  '0022401230',
  '0022401209',
  '0022400626',
  '0022400251',
  '0022400611',
  '0022400704',
  '0022400253',
  '0022400489',
  '0022400722',
  '0022400444',
  '0022400294',
  '0022401172',
  '0022400947',
  '0022400676',
  '0022400334',
  '0022400063',
  '0022400665',
  '0022400842',
  '0022400708',
  '0022400770',
  '0022400823',
  '0022400963',
  '0022400055',
  '0022400520',
  '0022400865',
  '0022400773',
  '0022400246',
  '0022401223',
  '0022401186',
  '0022400945',
  '0022400298',
  '0022400976',
  '0022400984',
  '0022400674',
  '0022400584',
  '0022400685',
  '0022400378',
  '0022400483',
  '0022400327',
  '0022400239',
  '0022400561',
  '0022400472',
  '0022400835',
  '0022400868',
  '0022400914',
  '0022401024',
  '0022401196',
  '0022400688',
  '0022400047',
  '0022400763',
  '0022401040',
  '0022400485',
  '0022400247',
  '0022400250',
  '0022400046',
  '0022400232',
  '0022400630',
  '0022400455',
  '0022400377',
  '0022400871',
  '0022400635',
  '0022400031',
  '0022400760',
  '0022400672',
  '0022400637',
  '0022400508',
  '0022401217',
  '0022400317',
  '0022400079',
  '0022400631',
  '0022400767',
  '0022400094',
  '0022400923',
  '0022400364',
  '0022400273',
  '0022401180',
  '0022400703',
  '0022400268',
  '0022400783',
  '0022400109',
  '0022401032',
  '0022400134',
  '0022400433',
  '0022401219',
  '0022400815',
  '0022400020',
  '0022400697',
  '0022400758',
  '0022400620',
  '0022400796',
  '0022400252',
  '0022400295',
  '0022400430',
  '0022400601',
  '0022401208',
  '0022400303',
  '0022400740',
  '0022400494',
  '0022400856',
  '0022400735',
  '0022400727',
  '0022400560',
  '0022400646',
  '0022400414',
  '0022400895',
  '0022400130',
  '0022400427',
  '0022400380',
  '0022401147',
  '0022400915',
  '0022400301',
  '0022401094',
  '0022400846',
  '0022400838',
  '0022400404',
  '0022400456',
  '0022400099',
  '0022400100',
  '0022401026',
  '0022400138',
  '0022400649',
  '0022400238',
  '0022400718',
  '0022401127',
  '0022400955',
  '0022400402',
  '0022401000',
  '0022400744',
  '0022400386',
  '0022400087',
  '0022400768',
  '0022400233',
  '0022401103',
  '0022400545',
  '0022400228',
  '0022400476',
  '0022400959',
  '0022401105',
  '0022400858',
  '0022400077',
  '0022400158',
  '0022400568',
  '0022400567',
  '0022400939',
  '0022401092',
  '0022401068',
  '0022400724',
  '0022400682',
  '0022401002',
  '0022400600',
  '0022400581',
  '0022400691',
  '0022400952',
  '0022400027',
  '0022401216',
  '0022400569',
  '0022400525',
  '0022400329',
  '0022401179',
  '0022400186',
  '0022400029',
  '0022401085',
  '0022400262',
  '0022400260',
  '0022400137',
  '0022400357',
  '0022400573',
  '0022400269',
  '0022400541',
  '0022400034',
  '0022401012',
  '0022400924',
  '0022400103',
  '0022400397',
  '0022400612',
  '0022400606',
  '0022400287',
  '0022400311',
  '0022400956',
  '0022400640',
  '0022400493',
  '0022400211',
  '0022401023',
  '0022400080',
  '0022400122',
  '0022400900',
  '0022400648',
  '0022400641',
  '0022400142',
  '0022400423',
  '0022400723',
  '0022400533',
  '0022401077',
  '0022400714',
  '0022400178',
  '0022401016',
  '0022400633',
  '0022400855',
  '0022401128',
  '0022400699',
  '0022401118',
  '0022400802',
  '0022400973',
  '0022400687',
  '0022400216',
  '0022400003',
  '0022400036',
  '0022400280',
  '0022400140',
  '0022400628',
  '0022400681',
  '0022400736',
  '0022400756',
  '0022400988',
  '0022400501',
  '0022400935',
  '0022400037',
  '0022400514',
  '0022401048',
  '0022401170',
  '0022400400',
  '0022400624',
  '0022400747',
  '0022400213',
  '0022401166',
  '0022400786',
  '0022400812',
  '0022401074',
  '0022401006',
  '0022400616',
  '0022401110',
  '0022400293',
  '0022400530',
  '0022400509',
  '0022400645',
  '0022400152',
  '0022400330',
  '0022400200',
  '0022400032',
  '0022401003',
  '0022400843',
  '0022400785',
  '0022400227',
  '0022401007',
  '0022400852',
  '0022400755',
  '0022400362',
  '0022400789',
  '0022400181',
  '0022400730',
  '0022400154',
  '0022400086',
  '0022401211',
  '0022401229',
  '0022400834',
  '0022400332',
  '0022400464',
  '0022400604',
  '0022400809',
  '0022401189',
  '0022401125',
  ...})

## Rotation Based on GameID

In [27]:
def get_rotation(game_id:str):
    full_rotation = gamerotation.GameRotation(game_id = game_id).get_data_frames()
    ht_rotation = full_rotation[1]
    ht_rotation['home_away_flg'] = 'H'
    at_rotation = full_rotation[0]
    at_rotation['home_away_flg'] = 'A'
    rotation_df = pd.concat([ht_rotation, at_rotation])
    rotation_df = rotation_df.sort_values(by = ['IN_TIME_REAL', 'OUT_TIME_REAL'], ascending = [True, True])
    rotation_df = rotation_df.reset_index(drop = True)
    rotation_df['IN_TIME_REAL'] = np.ceil(rotation_df['IN_TIME_REAL']/10)
    rotation_df['OUT_TIME_REAL'] = np.ceil(rotation_df['OUT_TIME_REAL']/10)

    #Calc. Breakpoints
    breakpoints = sorted(set(rotation_df['IN_TIME_REAL']).union(set(rotation_df['OUT_TIME_REAL'])))

    #Add Sleep Time
    time.sleep(1)

    return rotation_df, breakpoints

In [28]:
rotation_df, breakpoints = get_rotation('0022400061')

In [29]:
rotation_df

,GAME_ID,TEAM_ID,TEAM_CITY,TEAM_NAME,PERSON_ID,PLAYER_FIRST,PLAYER_LAST,IN_TIME_REAL,OUT_TIME_REAL,PLAYER_PTS,PT_DIFF,USG_PCT,home_away_flg
0,0022400061,1610612738,Boston,Celtics,201950,Jrue,Holiday,0.0,325.0,0,7.0,0.067,H
1,0022400061,1610612738,Boston,Celtics,1627759,Jaylen,Brown,0.0,325.0,5,7.0,0.333,H
2,0022400061,1610612752,New York,Knicks,1626157,Karl-Anthony,Towns,0.0,325.0,2,-7.0,0.182,A
3,0022400061,1610612752,New York,Knicks,1628384,OG,Anunoby,0.0,416.0,2,-7.0,0.133,A
4,0022400061,1610612738,Boston,Celtics,201143,Al,Horford,0.0,429.0,3,5.0,0.050,H
5,0022400061,1610612738,Boston,Celtics,1628401,Derrick,White,0.0,559.0,5,13.0,0.217,H
6,0022400061,1610612752,New York,Knicks,1628404,Josh,Hart,0.0,559.0,5,-13.0,0.300,A
7,0022400061,1610612752,New York,Knicks,1628973,Jalen,Brunson,0.0,559.0,6,-13.0,0.250,A
8,0022400061,1610612738,Boston,Celtics,1628369,Jayson,Tatum,0.0,720.0,15,19.0,0.300,H
9,0022400061,1610612752,New York,Knicks,1628969,Mikal,Bridges,0.0,807.0,0,-15.0,0.179,A
10,0022400061,1610612752,New York,Knicks,1630579,Jericho,Sims,325.0,559.0,0,-6.0,0.000,A
11,0022400061,1610612738,Boston,Celtics,1628436,Luke,Kornet,325.0,720.0,2,12.0,0.133,H
12,0022400061,1610612738,Boston,Celtics,1630202,Payton,Pritchard,325.0,720.0,3,12.0,0.133,H
13,0022400061,1610612752,New York,Knicks,1630540,Miles,McBride,416.0,1245.0,14,-17.0,0.259,A
14,0022400061,1610612738,Boston,Celtics,1630573,Sam,Hauser,429.0,1062.0,5,14.0,0.167,H
15,0022400061,1610612738,Boston,Celtics,201950,Jrue,Holiday,559.0,1062.0,10,6.0,0.250,H
16,0022400061,1610612752,New York,Knicks,1626157,Karl-Anthony,Towns,559.0,1062.0,4,-6.0,0.176,A
17,0022400061,1610612752,New York,Knicks,1626166,Cameron,Payne,559.0,1062.0,2,-6.0,0.235,A
18,0022400061,1610612752,New York,Knicks,1628384,OG,Anunoby,559.0,1062.0,0,-6.0,0.059,A
19,0022400061,1610612738,Boston,Celtics,201143,Al,Horford,720.0,1062.0,3,0.0,0.154,H
20,0022400061,1610612738,Boston,Celtics,1630214,Xavier,Tillman,720.0,1062.0,0,0.0,0.154,H
21,0022400061,1610612738,Boston,Celtics,1627759,Jaylen,Brown,720.0,1834.0,13,10.0,0.289,H
22,0022400061,1610612752,New York,Knicks,1642359,Pacome,Dadiet,807.0,1095.0,0,-2.0,0.111,A
23,0022400061,1610612738,Boston,Celtics,1628436,Luke,Kornet,1062.0,1245.0,0,5.0,0.000,H
24,0022400061,1610612738,Boston,Celtics,1630202,Payton,Pritchard,1062.0,1245.0,0,5.0,0.167,H
25,0022400061,1610612752,New York,Knicks,1630579,Jericho,Sims,1062.0,1245.0,2,-5.0,0.200,A
26,0022400061,1610612752,New York,Knicks,1628404,Josh,Hart,1062.0,1973.0,7,-10.0,0.129,A
27,0022400061,1610612752,New York,Knicks,1628973,Jalen,Brunson,1062.0,1973.0,16,-10.0,0.452,A
28,0022400061,1610612738,Boston,Celtics,1628401,Derrick,White,1062.0,2101.0,19,8.0,0.273,H
29,0022400061,1610612738,Boston,Celtics,1628369,Jayson,Tatum,1062.0,2160.0,22,7.0,0.306,H
30,0022400061,1610612752,New York,Knicks,1628969,Mikal,Bridges,1095.0,2365.0,16,-18.0,0.209,A
31,0022400061,1610612738,Boston,Celtics,201143,Al,Horford,1245.0,1834.0,0,5.0,0.105,H
32,0022400061,1610612738,Boston,Celtics,201950,Jrue,Holiday,1245.0,1834.0,6,5.0,0.105,H
33,0022400061,1610612752,New York,Knicks,1626157,Karl-Anthony,Towns,1245.0,1834.0,6,-5.0,0.190,A
34,0022400061,1610612752,New York,Knicks,1628384,OG,Anunoby,1245.0,1834.0,0,-5.0,0.048,A
35,0022400061,1610612738,Boston,Celtics,1628436,Luke,Kornet,1834.0,2160.0,2,-3.0,0.091,H
36,0022400061,1610612738,Boston,Celtics,1630202,Payton,Pritchard,1834.0,2160.0,0,-3.0,0.182,H
37,0022400061,1610612738,Boston,Celtics,1630573,Sam,Hauser,1834.0,2286.0,3,1.0,0.063,H
38,0022400061,1610612752,New York,Knicks,1630540,Miles,McBride,1834.0,2556.0,8,-1.0,0.185,A
39,0022400061,1610612752,New York,Knicks,1630579,Jericho,Sims,1834.0,2880.0,2,6.0,0.081,A
40,0022400061,1610612752,New York,Knicks,1628384,OG,Anunoby,1973.0,2515.0,2,-3.0,0.190,A
41,0022400061,1610612752,New York,Knicks,1626166,Cameron,Payne,1973.0,2713.0,9,6.0,0.259,A
42,0022400061,1610612738,Boston,Celtics,201950,Jrue,Holiday,2101.0,2515.0,2,5.0,0.067,H
43,0022400061,1610612738,Boston,Celtics,201143,Al,Horford,2160.0,2365.0,5,9.0,0.250,H
44,0022400061,1610612738,Boston,Celtics,1627759,Jaylen,Brown,2160.0,2515.0,5,6.0,0.417,H
45,0022400061,1610612738,Boston,Celtics,1630214,Xavier,Tillman,2160.0,2880.0,2,-3.0,0.154,H
46,0022400061,1610612738,Boston,Celtics,1630202,Payton,Pritchard,2286.0,2880.0,0,-7.0,0.286,H
47,0022400061,1610612738,Boston,Celtics,1628436,Luke,Kornet,2365.0,2620.0,0,-12.0,0.000,H
48,0022400061,1610612752,New York,Knicks,1642359,Pacome,Dadiet,2365.0,2880.0,3,12.0,0.111,A
49,0022400061,1610612738,Boston,Celtics,1630573,Sam,Hauser,2515.0,2880.0,2,-9.0,0.357,H
50,0022400061,1610612738,Boston,Celtics,1641775,Jordan,Walsh,2515.0,2880.0,0,-9.0,0.071,H
51,0022400061,1610612752,New York,Knicks,1630574,Ariel,Hukporti,2515.0,2880.0,0,9.0,0.000,A
52,0022400061,1610612752,New York,Knicks,1642278,Tyler,Kolek,2556.0,2880.0,3,7.0,0.364,A
53,0022400061,1610612738,Boston,Celtics,1629674,Neemias,Queta,2620.0,2880.0,0,0.0,0.000,H
54,0022400061,1610612752,New York,Knicks,1631210,Jacob,Toppin,2713.0,2880.0,0,0.0,0.200,A

In [30]:
breakpoints

[0.0,
 325.0,
 416.0,
 429.0,
 559.0,
 720.0,
 807.0,
 1062.0,
 1095.0,
 1245.0,
 1834.0,
 1973.0,
 2101.0,
 2160.0,
 2286.0,
 2365.0,
 2515.0,
 2556.0,
 2620.0,
 2713.0,
 2880.0]

## Stints and Point Differential from PBP Data

In [32]:
def get_stints_pt_diff(game_id:str, breakpoints:list):
    pbp = playbyplayv3.PlayByPlayV3(game_id = game_id).get_data_frames()[0]

    #Get Actual Point Differential
    pbp['time_completed'] = ((pbp['period']-1) * 12*60) + ((12*60) - pbp['clock'].str[2:4].astype(float)*60 - pbp['clock'].str[5:7].astype(float))
    pbp_formatted = pbp[['clock', 'time_completed', 'scoreHome', 'scoreAway', 'description', 'actionType']].copy()
    pbp_formatted['scoreHome'].replace('', np.nan, inplace = True)
    pbp_formatted['scoreAway'].replace('', np.nan, inplace = True)
    pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
    pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)
    
    pbp_formatted['scoreHome'] = pbp_formatted['scoreHome'].astype(int)
    pbp_formatted['scoreAway'] = pbp_formatted['scoreAway'].astype(int)
    
    
    
    
    pbp_formatted['STINT_START_TIME'] = pbp_formatted['time_completed'].shift(1)
    pbp_formatted['STINT_START_TIME'] = pbp_formatted['STINT_START_TIME'].fillna(0)
    
    pbp_formatted.rename(columns = {'time_completed': 'STINT_END_TIME'}, inplace = True)
    pbp_formatted = pbp_formatted.loc[pbp_formatted['STINT_END_TIME'].isin(breakpoints)]
    
    
    pt_diff_df = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])
    
    for i in range(len(breakpoints) - 1):
        t = breakpoints[i]
        t_plus_1 = breakpoints[i+1]
    
        temp = pbp_formatted.loc[(pbp_formatted['STINT_START_TIME'] >= t) & (pbp_formatted['STINT_END_TIME'] <= t_plus_1)]
        res = pd.DataFrame(columns = ['STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])
    
        res.loc[0, 'STINT_START_TIME'] = t 
        res.loc[0, 'STINT_END_TIME'] = t_plus_1
    
        diff = 0
    
        if t == 0:
            diff = np.max(temp['scoreHome']) - np.max(temp['scoreAway'])
        
        else:
            end_home_score = temp.loc[(temp['STINT_END_TIME'] == t_plus_1) & (temp['actionType'].isin(['Substitution', 'period']))]['scoreHome'].values[0]
            end_away_score = temp.loc[(temp['STINT_END_TIME'] == t_plus_1) & (temp['actionType'].isin(['Substitution', 'period']))]['scoreAway'].values[0]
            # diff = (np.max(temp['scoreHome']) - np.min(temp['scoreHome'])) - (np.max(temp['scoreAway']) - np.min(temp['scoreAway']))
            diff = (end_home_score - np.min(temp['scoreHome'])) - (end_away_score - np.min(temp['scoreAway']))
        
        res.loc[0, 'PT_DIFF'] = diff 
    
        pt_diff_df = pd.concat([pt_diff_df, res], axis = 0)
        pt_diff_df = pt_diff_df.reset_index(drop = True)

    #Add Sleep Time
    time.sleep(1)
    
    return pt_diff_df

In [33]:
pt_diff_df = get_stints_pt_diff('0022400061', breakpoints)
pt_diff_df

/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)

   STINT_START_TIME STINT_END_TIME PT_DIFF
0               0.0          325.0       7
1             325.0          416.0       1
2             416.0          429.0      -2
3             429.0          559.0       8
4             559.0          720.0       6
5             720.0          807.0      -4
6             807.0         1062.0       4
7            1062.0         1095.0      -1
8            1095.0         1245.0       5
9            1245.0         1834.0       6
10           1834.0         1973.0       0
11           1973.0         2101.0      -2
12           2101.0         2160.0      -1
13           2160.0         2286.0       4
14           2286.0         2365.0       5
15           2365.0         2515.0      -3
16           2515.0         2556.0      -2
17           2556.0         2620.0      -7
18           2620.0         2713.0       0
19           2713.0         2880.0       0

## PlayerID In-Time Out-Time

In [35]:
def get_player_id_in_out_time(rotation_df:pd.DataFrame):
    players = list(set(rotation_df.PERSON_ID))

    player_id_cols = ['PERSON_ID_'+str(p) for p in players]
    player_flags_df = pd.get_dummies(rotation_df, columns = ['PERSON_ID'], dtype = int).copy()
    player_flags_df = player_flags_df.groupby(['IN_TIME_REAL', 'OUT_TIME_REAL'])[player_id_cols].sum().reset_index()
    return players, player_flags_df

In [36]:
players, _ = get_player_id_in_out_time(rotation_df)
players

[1630214,
 1628436,
 1642278,
 1628969,
 1626157,
 1628973,
 1641775,
 1626166,
 201143,
 1630540,
 1628369,
 201950,
 1628384,
 1629674,
 1631210,
 1630573,
 1630574,
 1627759,
 1628401,
 1630579,
 1628404,
 1642359,
 1630202]

## Final Stint-wise Point Differential Function

In [38]:
def final_stint_pt_diff(players:list, breakpoints:list, rotation_df:pd.DataFrame, pt_diff_df:pd.DataFrame, game_id:str, season:str):
    final_stints_df = pd.DataFrame(columns = ['SEASON', 'GAME_ID', 'STINT_START_TIME', 'STINT_END_TIME'] + players + ['PT_DIFF'])

    for i in tqdm(range(len(breakpoints) - 1)):
      t = breakpoints[i]
      t_plus_1 = breakpoints[i+1]
      stint_players = rotation_df.loc[(rotation_df['IN_TIME_REAL'] <= t) & (rotation_df['OUT_TIME_REAL'] > t)][['PERSON_ID']].values.flatten().tolist()
      home_away_flgs = rotation_df.loc[(rotation_df['IN_TIME_REAL'] <= t) & (rotation_df['OUT_TIME_REAL'] > t)][['home_away_flg']].values.tolist()
      # pt_diff = stints_df.loc[(stints_df['STINT_START_TIME_FIXED'] == t) & (stints_df['STINT_END_TIME'] == t_plus_1)]['PT_DIFF'].sum()
      pt_diff = pt_diff_df.loc[(pt_diff_df['STINT_START_TIME'] == t) & (pt_diff_df['STINT_END_TIME'] == t_plus_1)]['PT_DIFF'].values[0]
    
      X = pd.DataFrame(columns = ['SEASON', 'GAME_ID', 'STINT_START_TIME', 'STINT_END_TIME'] + players + ['PT_DIFF'])
      #Assign Season and GameID
      X.loc[0, 'SEASON'] = season
      X.loc[0, 'GAME_ID'] = game_id
      X.loc[0, 'STINT_START_TIME'] = t
      X.loc[0, 'STINT_END_TIME'] = t_plus_1
      X.loc[0, 'PT_DIFF'] = pt_diff
    
      for player in players:
        if player in stint_players:
          if home_away_flgs[stint_players.index(player)] == 'H':
            X.loc[0, player] = 1
          else:
            X.loc[0, player] = -1
        else:
          X.loc[0, player] = 0
    
      final_stints_df = pd.concat([final_stints_df, X], axis = 0)
    
    final_stints_df = final_stints_df.reset_index(drop = True)
    return final_stints_df

In [39]:
final_stint_pt_diff(players, breakpoints, rotation_df, pt_diff_df, '0022400061', '2024-25')

100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 766.64it/s]

,SEASON,GAME_ID,STINT_START_TIME,STINT_END_TIME,1630214,1628436,1642278,1628969,1626157,1628973,...,1631210,1630573,1630574,1627759,1628401,1630579,1628404,1642359,1630202,PT_DIFF
0,2024-25,0022400061,0.0,325.0,0,0,0,-1,-1,-1,...,0,0,0,-1,-1,0,-1,0,0,7
1,2024-25,0022400061,325.0,416.0,0,-1,0,-1,0,-1,...,0,0,0,0,-1,-1,-1,0,-1,1
2,2024-25,0022400061,416.0,429.0,0,-1,0,-1,0,-1,...,0,0,0,0,-1,-1,-1,0,-1,-2
3,2024-25,0022400061,429.0,559.0,0,-1,0,-1,0,-1,...,0,-1,0,0,-1,-1,-1,0,-1,8
4,2024-25,0022400061,559.0,720.0,0,-1,0,-1,-1,0,...,0,-1,0,0,0,0,0,0,-1,6
5,2024-25,0022400061,720.0,807.0,-1,0,0,-1,-1,0,...,0,-1,0,-1,0,0,0,0,0,-4
6,2024-25,0022400061,807.0,1062.0,-1,0,0,0,-1,0,...,0,-1,0,-1,0,0,0,-1,0,4
7,2024-25,0022400061,1062.0,1095.0,0,-1,0,0,0,-1,...,0,0,0,-1,-1,-1,-1,-1,-1,-1
8,2024-25,0022400061,1095.0,1245.0,0,-1,0,-1,0,-1,...,0,0,0,-1,-1,-1,-1,0,-1,5
9,2024-25,0022400061,1245.0,1834.0,0,0,0,-1,-1,-1,...,0,0,0,-1,-1,0,-1,0,0,6
10,2024-25,0022400061,1834.0,1973.0,0,-1,0,-1,0,-1,...,0,-1,0,0,-1,-1,-1,0,-1,0
11,2024-25,0022400061,1973.0,2101.0,0,-1,0,-1,0,0,...,0,-1,0,0,-1,-1,0,0,-1,-2
12,2024-25,0022400061,2101.0,2160.0,0,-1,0,-1,0,0,...,0,-1,0,0,0,-1,0,0,-1,-1
13,2024-25,0022400061,2160.0,2286.0,-1,0,0,-1,0,0,...,0,-1,0,-1,0,-1,0,0,0,4
14,2024-25,0022400061,2286.0,2365.0,-1,0,0,-1,0,0,...,0,0,0,-1,0,-1,0,0,-1,5
15,2024-25,0022400061,2365.0,2515.0,-1,-1,0,0,0,0,...,0,0,0,-1,0,-1,0,-1,-1,-3
16,2024-25,0022400061,2515.0,2556.0,-1,-1,0,0,0,0,...,0,-1,-1,0,0,-1,0,-1,-1,-2
17,2024-25,0022400061,2556.0,2620.0,-1,-1,-1,0,0,0,...,0,-1,-1,0,0,-1,0,-1,-1,-7
18,2024-25,0022400061,2620.0,2713.0,-1,0,-1,0,0,0,...,0,-1,-1,0,0,-1,0,-1,-1,0
19,2024-25,0022400061,2713.0,2880.0,-1,0,-1,0,0,0,...,-1,-1,-1,0,0,-1,0,-1,-1,0

## Process Game

In [41]:
def process_game(game_id: str, szn: int) -> pd.DataFrame:
    """Compute one game's stint-wise point differential dataframe. Also provides the point differential per 48 minutes."""
    # If you still need to throttle a bit to be polite to an API, uncomment:
    # time.sleep(0.10)

    rotation_df, breakpoints = get_rotation(game_id)                             # Get Rotation and Breakpoints
    pt_diff_df = get_stints_pt_diff(game_id, breakpoints)                        # Get Point Differential for each Stint
    players, _ = get_player_id_in_out_time(rotation_df)                          # Get List of Players
    game_res_df = final_stint_pt_diff(players, breakpoints, rotation_df,
                                      pt_diff_df, game_id, szn)                  # Final per-game DF

    
    game_res_df['STINT_DURATION'] = game_res_df['STINT_END_TIME'] - game_res_df['STINT_START_TIME']                                          # Stint Duration in seconds
    game_res_df['PT_DIFF_PER_48'] = (48 * 60 * game_res_df['PT_DIFF'])/(game_res_df['STINT_END_TIME'] - game_res_df['STINT_START_TIME'])     # Final per48 Point Differential
    return game_res_df

In [71]:
process_game('0022400061', '2024-25')

/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].replace('', np.nan, inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreHome'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)
/var/folders/bl/md9bs_8x7v31z42n_0_459yw0000gn/T/ipykernel_44690/3001117299.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pbp_formatted['scoreAway'].fillna(method = 'ffill', inplace = True)
100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 356.49it/s]

,SEASON,GAME_ID,STINT_START_TIME,STINT_END_TIME,1630214,1628436,1642278,1628969,1626157,1628973,...,1630574,1627759,1628401,1630579,1628404,1642359,1630202,PT_DIFF,STINT_DURATION,PT_DIFF_PER_48
0,2024-25,0022400061,0.0,325.0,0,0,0,-1,-1,-1,...,0,-1,-1,0,-1,0,0,7,325.0,62.030769
1,2024-25,0022400061,325.0,416.0,0,-1,0,-1,0,-1,...,0,0,-1,-1,-1,0,-1,1,91.0,31.648352
2,2024-25,0022400061,416.0,429.0,0,-1,0,-1,0,-1,...,0,0,-1,-1,-1,0,-1,-2,13.0,-443.076923
3,2024-25,0022400061,429.0,559.0,0,-1,0,-1,0,-1,...,0,0,-1,-1,-1,0,-1,8,130.0,177.230769
4,2024-25,0022400061,559.0,720.0,0,-1,0,-1,-1,0,...,0,0,0,0,0,0,-1,6,161.0,107.329193
5,2024-25,0022400061,720.0,807.0,-1,0,0,-1,-1,0,...,0,-1,0,0,0,0,0,-4,87.0,-132.413793
6,2024-25,0022400061,807.0,1062.0,-1,0,0,0,-1,0,...,0,-1,0,0,0,-1,0,4,255.0,45.176471
7,2024-25,0022400061,1062.0,1095.0,0,-1,0,0,0,-1,...,0,-1,-1,-1,-1,-1,-1,-1,33.0,-87.272727
8,2024-25,0022400061,1095.0,1245.0,0,-1,0,-1,0,-1,...,0,-1,-1,-1,-1,0,-1,5,150.0,96.0
9,2024-25,0022400061,1245.0,1834.0,0,0,0,-1,-1,-1,...,0,-1,-1,0,-1,0,0,6,589.0,29.337861
10,2024-25,0022400061,1834.0,1973.0,0,-1,0,-1,0,-1,...,0,0,-1,-1,-1,0,-1,0,139.0,0.0
11,2024-25,0022400061,1973.0,2101.0,0,-1,0,-1,0,0,...,0,0,-1,-1,0,0,-1,-2,128.0,-45.0
12,2024-25,0022400061,2101.0,2160.0,0,-1,0,-1,0,0,...,0,0,0,-1,0,0,-1,-1,59.0,-48.813559
13,2024-25,0022400061,2160.0,2286.0,-1,0,0,-1,0,0,...,0,-1,0,-1,0,0,0,4,126.0,91.428571
14,2024-25,0022400061,2286.0,2365.0,-1,0,0,-1,0,0,...,0,-1,0,-1,0,0,-1,5,79.0,182.278481
15,2024-25,0022400061,2365.0,2515.0,-1,-1,0,0,0,0,...,0,-1,0,-1,0,-1,-1,-3,150.0,-57.6
16,2024-25,0022400061,2515.0,2556.0,-1,-1,0,0,0,0,...,-1,0,0,-1,0,-1,-1,-2,41.0,-140.487805
17,2024-25,0022400061,2556.0,2620.0,-1,-1,-1,0,0,0,...,-1,0,0,-1,0,-1,-1,-7,64.0,-315.0
18,2024-25,0022400061,2620.0,2713.0,-1,0,-1,0,0,0,...,-1,0,0,-1,0,-1,-1,0,93.0,0.0
19,2024-25,0022400061,2713.0,2880.0,-1,0,-1,0,0,0,...,-1,0,0,-1,0,-1,-1,0,167.0,0.0

## Pulling All Functions together to Scrape for Multiple Games

In [44]:
final_df = pd.DataFrame(columns = ['SEASON', 'GAME_ID', 'STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])

In [45]:
SEASONS = ['2022-23', '2023-24', '2024-25']

### Serial Processing

In [47]:
# for szn in SEASONS:
#     games, game_ids = gamelog_gameid(szn)

#     print(f"Now Running Season: {szn}")

#     for game_id in tqdm(game_ids):
#         rotation_df, breakpoints = get_rotation(game_id) #Get Rotation and Breakpoints
#         pt_diff_df = get_stints_pt_diff(game_id, breakpoints) #Get Point Differential for each Stint
#         players, _ = get_player_id_in_out_time(rotation_df) #Get List of Players

#         game_res_df = final_stint_pt_diff(players, breakpoints, rotation_df, pt_diff_df, game_id, szn) #Final Stint-Wise Point Differential for the Game with Player Flags

#         final_df = pd.concat([final_df, game_res_df], axis = 0, ignore_index=True)


#         time.sleep(1) #Sleep 1 second in between games

#     time.sleep(5) #Sleep 5 Seconds in-between seasons

### Parallel Processing

In [49]:
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
import time
import warnings
warnings.filterwarnings("ignore")

# Tune this based on your API limits / machine
MAX_WORKERS = 8

final_df_list = []  # collect per-season concatenations here
all_failed_games = {} #Keep Track of Failed Games Across all seasons on SEASONS

for szn in SEASONS:
    print(f"\nNow Running Season: {szn}")
    _, game_ids = gamelog_gameid(szn)

    time.sleep(5) #Sleep for 5 seconds after first API call for Game Log for a Season

    season_frames = []
    failures = []

    # Parallelize over games in this season
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futures = {ex.submit(process_game, gid, szn): gid for gid in game_ids}

        # Progress bar advances as futures complete (order-agnostic)
        for fut in tqdm(as_completed(futures), total=len(futures), desc=f"Season {szn}"):
            gid = futures[fut]
            try:
                season_frames.append(fut.result())
            except Exception as e:
                failures.append((gid, e))

    # Concatenate once per season for speed
    if season_frames:
        season_df = pd.concat(season_frames, axis=0, ignore_index=True)
        final_df_list.append(season_df)

    if failures:
        # You can log these and optionally retry
        print(f"[WARN] {len(failures)} games failed in {szn}. Examples:")
        for gid, err in failures[:5]:
            print(f"  - {gid}: {err}")

        #Append All Failures to all_failed_games
        all_failed_games[szn] = failures

    # If you still want a short pause between seasons, keep this:
    time.sleep(5)

# Single concat at the very end
final_df = pd.concat(final_df_list, axis=0, ignore_index=True)

Now Running Season: 2022-23

Season 2022-23:   0%|                                  | 0/1230 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 491.01it/s]
Season 2022-23:   0%|                        | 1/1230 [00:07<2:26:45,  7.16s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 495.97it/s]
Season 2022-23:   0%|                        | 2/1230 [00:07<1:05:35,  3.21s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 760.03it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 428.56it/s]
Season 2022-23:   0%|                        | 5/1230 [00:17<1:07:41,  3.32s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 830.79it/s]
Season 2022-23:   0%|▏                         | 6/1230 [00:19<56:54,  2.79s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 481.43it/s]
Season 2022-23:   1%|▏                         | 7/1230 [00:19<42:32,  2.09s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 715.80it/s]
Season 2022-23:   1%|▏                         | 8/1230 [00:19<30:38,  1.50s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 736.01it/s]
Season 2022-23:   1%|▏                         | 9/1230 [00:20<23:37,  1.16s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 441.74it/s]
Season 2022-23:   1%|▏                        | 10/1230 [00:21<22:56,  1.13s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 780.68it/s]
Season 2022-23:   1%|▏                        | 11/1230 [00:21<16:57,  1.20it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 440.96it/s]
Season 2022-23:   1%|▏                        | 12/1230 [00:21<16:16,  1.25it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 445.67it/s]
Season 2022-23:   1%|▎                        | 15/1230 [00:23<12:21,  1.64it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 725.48it/s]
Season 2022-23:   1%|▎                        | 16/1230 [00:24<11:36,  1.74it/s]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 484.04it/s]
Season 2022-23:   1%|▎                        | 17/1230 [00:25<14:20,  1.41it/s]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 388.70it/s]
Season 2022-23:   1%|▎                        | 18/1230 [00:26<13:45,  1.47it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 627.06it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 447.32it/s]
Season 2022-23:   2%|▍                        | 20/1230 [00:27<13:00,  1.55it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 389.40it/s]
Season 2022-23:   2%|▍                        | 21/1230 [00:27<12:43,  1.58it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 464.19it/s]
Season 2022-23:   2%|▍                        | 22/1230 [00:28<12:20,  1.63it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 523.94it/s]
Season 2022-23:   2%|▍                        | 23/1230 [00:28<10:40,  1.89it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 581.43it/s]
Season 2022-23:   2%|▍                        | 24/1230 [00:28<09:01,  2.23it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 857.94it/s]
Season 2022-23:   2%|▌                        | 25/1230 [00:33<31:54,  1.59s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 445.59it/s]
Season 2022-23:   2%|▌                        | 26/1230 [00:34<28:29,  1.42s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 811.30it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 465.76it/s]
Season 2022-23:   2%|▌                        | 28/1230 [00:35<18:50,  1.06it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 526.97it/s]
Season 2022-23:   2%|▌                        | 29/1230 [00:35<18:09,  1.10it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 433.02it/s]
Season 2022-23:   2%|▌                        | 30/1230 [00:37<19:50,  1.01it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 842.00it/s]

100%|██████████████████████████████████████████| 19/19 [00:00<00:00, 401.77it/s]
Season 2022-23:   3%|▋                        | 32/1230 [00:37<13:52,  1.44it/s]
100%|██████████████████████████████████████████| 40/40 [00:00<00:00, 513.72it/s]
Season 2022-23:   3%|▋                        | 34/1230 [00:39<15:51,  1.26it/s]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 485.22it/s]
Season 2022-23:   3%|▋                        | 35/1230 [00:40<16:01,  1.24it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 529.74it/s]
Season 2022-23:   3%|▋                        | 36/1230 [00:40<14:09,  1.40it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 781.19it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 413.98it/s]
Season 2022-23:   3%|▊                        | 38/1230 [00:42<13:10,  1.51it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 861.02it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 445.46it/s]
Season 2022-23:   3%|▊                        | 41/1230 [00:42<09:02,  2.19it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 456.17it/s]
Season 2022-23:   3%|▊                        | 42/1230 [00:44<12:43,  1.56it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 561.20it/s]
Season 2022-23:   3%|▊                        | 43/1230 [00:44<11:02,  1.79it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 825.92it/s]

100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 432.46it/s]
Season 2022-23:   4%|▉                        | 45/1230 [00:46<15:20,  1.29it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 558.04it/s]
Season 2022-23:   4%|▉                        | 46/1230 [00:51<31:37,  1.60s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 788.68it/s]

100%|██████████████████████████████████████████| 39/39 [00:00<00:00, 510.66it/s]
Season 2022-23:   4%|▉                        | 48/1230 [00:51<21:32,  1.09s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 567.21it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 550.47it/s]
Season 2022-23:   4%|█                        | 50/1230 [00:52<15:09,  1.30it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 547.22it/s]
Season 2022-23:   4%|█                        | 52/1230 [00:53<14:27,  1.36it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 788.65it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 777.10it/s]
Season 2022-23:   4%|█                        | 54/1230 [00:53<10:09,  1.93it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 677.76it/s]
Season 2022-23:   4%|█                        | 55/1230 [00:53<09:03,  2.16it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 471.46it/s]
Season 2022-23:   5%|█▏                       | 56/1230 [00:56<15:58,  1.22it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 765.49it/s]
Season 2022-23:   5%|█▏                       | 57/1230 [00:59<29:08,  1.49s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 461.21it/s]
Season 2022-23:   5%|█▏                       | 58/1230 [01:00<24:58,  1.28s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 490.76it/s]
Season 2022-23:   5%|█▏                       | 59/1230 [01:00<20:28,  1.05s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 487.28it/s]
Season 2022-23:   5%|█▏                       | 60/1230 [01:01<17:05,  1.14it/s]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 487.08it/s]
Season 2022-23:   5%|█▏                       | 61/1230 [01:01<16:12,  1.20it/s]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 752.43it/s]
Season 2022-23:   5%|█▎                       | 62/1230 [01:02<15:17,  1.27it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 825.89it/s]
Season 2022-23:   5%|█▎                       | 63/1230 [01:02<11:43,  1.66it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 459.33it/s]
Season 2022-23:   5%|█▎                       | 65/1230 [01:03<10:08,  1.92it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 443.59it/s]
Season 2022-23:   5%|█▎                       | 66/1230 [01:05<14:16,  1.36it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 739.53it/s]
Season 2022-23:   5%|█▎                       | 67/1230 [01:05<10:58,  1.77it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 460.28it/s]
Season 2022-23:   6%|█▍                       | 68/1230 [01:07<20:11,  1.04s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 529.92it/s]
Season 2022-23:   6%|█▍                       | 69/1230 [01:08<18:20,  1.05it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 863.59it/s]
Season 2022-23:   6%|█▍                       | 70/1230 [01:09<21:30,  1.11s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 455.91it/s]
Season 2022-23:   6%|█▍                       | 71/1230 [01:10<19:42,  1.02s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 570.46it/s]
Season 2022-23:   6%|█▍                       | 72/1230 [01:10<15:07,  1.28it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 546.77it/s]
Season 2022-23:   6%|█▍                       | 73/1230 [01:10<11:57,  1.61it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 821.08it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 451.30it/s]
Season 2022-23:   6%|█▌                       | 75/1230 [01:12<11:54,  1.62it/s]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 522.62it/s]
Season 2022-23:   6%|█▌                       | 76/1230 [01:13<16:39,  1.15it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 500.88it/s]
Season 2022-23:   6%|█▌                       | 77/1230 [01:14<16:45,  1.15it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 472.25it/s]
Season 2022-23:   6%|█▌                       | 78/1230 [01:17<26:30,  1.38s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 532.96it/s]
Season 2022-23:   6%|█▌                       | 79/1230 [01:19<29:21,  1.53s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 429.34it/s]


100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 794.00it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 553.54it/s]
Season 2022-23:   7%|█▋                       | 82/1230 [01:23<24:28,  1.28s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 603.63it/s]
Season 2022-23:   7%|█▋                       | 83/1230 [01:24<22:59,  1.20s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 426.79it/s]
Season 2022-23:   7%|█▋                       | 84/1230 [01:25<20:58,  1.10s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 697.06it/s]
Season 2022-23:   7%|█▋                       | 85/1230 [01:25<16:09,  1.18it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 488.62it/s]
Season 2022-23:   7%|█▋                       | 86/1230 [01:25<13:34,  1.41it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 445.69it/s]
Season 2022-23:   7%|█▊                       | 87/1230 [01:27<18:05,  1.05it/s]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 404.96it/s]
Season 2022-23:   7%|█▊                       | 88/1230 [01:27<15:54,  1.20it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 467.79it/s]
Season 2022-23:   7%|█▊                       | 89/1230 [01:32<38:51,  2.04s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 544.10it/s]
Season 2022-23:   7%|█▊                       | 90/1230 [01:33<29:02,  1.53s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 832.06it/s]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 483.82it/s]
Season 2022-23:   7%|█▊                       | 92/1230 [01:34<20:36,  1.09s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 476.81it/s]
Season 2022-23:   8%|█▉                       | 93/1230 [01:35<21:11,  1.12s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 379.76it/s]
Season 2022-23:   8%|█▉                       | 94/1230 [01:36<21:49,  1.15s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 822.08it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 453.21it/s]
Season 2022-23:   8%|█▉                       | 96/1230 [01:37<15:05,  1.25it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 447.06it/s]
Season 2022-23:   8%|█▉                       | 97/1230 [01:38<14:55,  1.27it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 502.49it/s]
Season 2022-23:   8%|█▉                       | 98/1230 [01:40<22:44,  1.21s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 607.67it/s]
Season 2022-23:   8%|██                       | 99/1230 [01:40<17:39,  1.07it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 416.05it/s]
Season 2022-23:   8%|█▉                      | 100/1230 [01:41<15:31,  1.21it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 829.65it/s]

100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 461.48it/s]


100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 772.52it/s]

100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 854.36it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 846.07it/s]
Season 2022-23:   9%|██                      | 105/1230 [01:43<09:47,  1.91it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 567.72it/s]
Season 2022-23:   9%|██                      | 106/1230 [01:46<16:49,  1.11it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 435.23it/s]
Season 2022-23:   9%|██                      | 107/1230 [01:46<14:55,  1.25it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 828.55it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 524.19it/s]
Season 2022-23:   9%|██▏                     | 109/1230 [01:47<10:42,  1.74it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 439.31it/s]
Season 2022-23:   9%|██▏                     | 110/1230 [01:49<18:33,  1.01it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 431.89it/s]
Season 2022-23:   9%|██▏                     | 111/1230 [01:52<27:09,  1.46s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 783.21it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 859.77it/s]
Season 2022-23:   9%|██▏                     | 113/1230 [01:52<17:00,  1.09it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 397.19it/s]
Season 2022-23:   9%|██▏                     | 114/1230 [01:53<15:57,  1.17it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 515.19it/s]
Season 2022-23:   9%|██▏                     | 115/1230 [01:53<13:31,  1.37it/s]
100%|██████████████████████████████████████████| 39/39 [00:00<00:00, 875.90it/s]

100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 481.81it/s]
Season 2022-23:  10%|██▎                     | 117/1230 [01:55<13:49,  1.34it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 466.44it/s]
Season 2022-23:  10%|██▎                     | 118/1230 [01:56<14:10,  1.31it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 538.75it/s]
Season 2022-23:  10%|██▎                     | 120/1230 [01:56<09:49,  1.88it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 824.14it/s]

100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 482.60it/s]
Season 2022-23:  10%|██▍                     | 122/1230 [01:57<10:40,  1.73it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 795.81it/s]
Season 2022-23:  10%|██▍                     | 123/1230 [01:59<14:04,  1.31it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 464.93it/s]
Season 2022-23:  10%|██▍                     | 124/1230 [02:00<15:16,  1.21it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 586.04it/s]
Season 2022-23:  10%|██▍                     | 125/1230 [02:00<12:51,  1.43it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 506.01it/s]
Season 2022-23:  10%|██▍                     | 127/1230 [02:02<15:36,  1.18it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 485.65it/s]
Season 2022-23:  10%|██▍                     | 128/1230 [02:04<17:02,  1.08it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 594.50it/s]
Season 2022-23:  10%|██▌                     | 129/1230 [02:04<14:01,  1.31it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 506.70it/s]
Season 2022-23:  11%|██▌                     | 130/1230 [02:04<11:46,  1.56it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 483.21it/s]
Season 2022-23:  11%|██▌                     | 131/1230 [02:05<14:08,  1.30it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 490.85it/s]
Season 2022-23:  11%|██▌                     | 132/1230 [02:06<16:16,  1.12it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 446.98it/s]
Season 2022-23:  11%|██▌                     | 133/1230 [02:07<16:05,  1.14it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 415.60it/s]
Season 2022-23:  11%|██▌                     | 134/1230 [02:08<14:55,  1.22it/s]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 711.32it/s]
Season 2022-23:  11%|██▋                     | 135/1230 [02:11<27:33,  1.51s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 744.23it/s]

100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 848.49it/s]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 498.33it/s]
Season 2022-23:  11%|██▋                     | 138/1230 [02:12<15:42,  1.16it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 500.35it/s]
Season 2022-23:  11%|██▋                     | 139/1230 [02:13<15:50,  1.15it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 484.42it/s]
Season 2022-23:  11%|██▋                     | 140/1230 [02:14<15:55,  1.14it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 771.84it/s]
Season 2022-23:  11%|██▊                     | 141/1230 [02:14<12:51,  1.41it/s]
100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 442.15it/s]
Season 2022-23:  12%|██▊                     | 142/1230 [02:15<13:58,  1.30it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 387.15it/s]
Season 2022-23:  12%|██▊                     | 143/1230 [02:16<13:52,  1.31it/s]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 825.44it/s]
Season 2022-23:  12%|██▊                     | 144/1230 [02:16<10:38,  1.70it/s]

[WARN] 113 games failed in 2022-23. Examples:
  - 0022200039: index 0 is out of bounds for axis 0 with size 0
  - 0022200497: index 0 is out of bounds for axis 0 with size 0
  - 0022201167: index 0 is out of bounds for axis 0 with size 0
  - 0022201072: index 0 is out of bounds for axis 0 with size 0
  - 0022200869: index 0 is out of bounds for axis 0 with size 0

Now Running Season: 2023-24

Season 2023-24:   0%|                                  | 0/1230 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 784.61it/s]
Season 2023-24:   0%|                        | 1/1230 [00:10<3:44:17, 10.95s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 774.82it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 809.04it/s]
Season 2023-24:   0%|                          | 3/1230 [00:11<59:57,  2.93s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 436.55it/s]
Season 2023-24:   0%|                          | 4/1230 [00:11<44:47,  2.19s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 461.37it/s]
Season 2023-24:   0%|                          | 5/1230 [00:13<38:43,  1.90s/it]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 659.35it/s]

100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 424.25it/s]
Season 2023-24:   1%|▏                         | 7/1230 [00:13<22:34,  1.11s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 515.46it/s]
Season 2023-24:   1%|▏                         | 8/1230 [00:14<18:00,  1.13it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 404.06it/s]
Season 2023-24:   1%|▏                         | 9/1230 [00:22<56:39,  2.78s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 417.72it/s]
Season 2023-24:   1%|▏                        | 10/1230 [00:23<48:01,  2.36s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 482.07it/s]
Season 2023-24:   1%|▏                        | 11/1230 [00:23<36:17,  1.79s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 383.72it/s]
Season 2023-24:   1%|▏                        | 12/1230 [00:25<35:28,  1.75s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 439.19it/s]
Season 2023-24:   1%|▎                        | 13/1230 [00:27<39:34,  1.95s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 557.28it/s]
Season 2023-24:   1%|▎                        | 14/1230 [00:27<29:18,  1.45s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 784.67it/s]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 438.47it/s]
Season 2023-24:   1%|▎                        | 16/1230 [00:28<20:23,  1.01s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 481.86it/s]
Season 2023-24:   1%|▎                        | 17/1230 [00:30<23:07,  1.14s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 421.98it/s]
Season 2023-24:   1%|▎                        | 18/1230 [00:32<26:24,  1.31s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 460.53it/s]
Season 2023-24:   2%|▍                        | 19/1230 [00:35<37:05,  1.84s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 440.36it/s]
Season 2023-24:   2%|▍                        | 20/1230 [00:37<38:08,  1.89s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 379.66it/s]
Season 2023-24:   2%|▍                        | 21/1230 [00:39<36:01,  1.79s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 452.51it/s]
Season 2023-24:   2%|▍                        | 22/1230 [00:39<30:17,  1.50s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 477.12it/s]
Season 2023-24:   2%|▍                        | 23/1230 [00:40<22:51,  1.14s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 843.05it/s]

100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 424.72it/s]
Season 2023-24:   2%|▌                        | 25/1230 [00:46<39:33,  1.97s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 426.53it/s]
Season 2023-24:   2%|▌                        | 26/1230 [00:47<36:21,  1.81s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 827.52it/s]
Season 2023-24:   2%|▌                        | 27/1230 [00:49<37:14,  1.86s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 582.94it/s]
Season 2023-24:   2%|▌                        | 28/1230 [00:50<32:49,  1.64s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 511.18it/s]
Season 2023-24:   2%|▌                        | 29/1230 [00:52<32:56,  1.65s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 437.60it/s]


100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 726.52it/s]

100%|██████████████████████████████████████████| 42/42 [00:00<00:00, 527.15it/s]
Season 2023-24:   3%|▋                        | 33/1230 [01:01<43:29,  2.18s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 428.08it/s]
Season 2023-24:   3%|▋                        | 34/1230 [01:03<41:33,  2.08s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 400.69it/s]
Season 2023-24:   3%|▋                        | 35/1230 [01:05<41:18,  2.07s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 643.80it/s]
Season 2023-24:   3%|▋                        | 36/1230 [01:07<44:04,  2.21s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 591.77it/s]
Season 2023-24:   3%|▊                        | 37/1230 [01:08<33:56,  1.71s/it]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 415.84it/s]
Season 2023-24:   3%|▊                        | 38/1230 [01:08<28:47,  1.45s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 428.27it/s]
Season 2023-24:   3%|▊                        | 39/1230 [01:09<25:00,  1.26s/it]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 450.41it/s]
Season 2023-24:   3%|▊                        | 40/1230 [01:09<19:48,  1.00it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 441.40it/s]
Season 2023-24:   3%|▊                        | 41/1230 [01:13<32:45,  1.65s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 560.18it/s]
Season 2023-24:   3%|▊                        | 42/1230 [01:18<53:52,  2.72s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 796.18it/s]
Season 2023-24:   3%|▊                        | 43/1230 [01:18<38:38,  1.95s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 422.81it/s]
Season 2023-24:   4%|▉                        | 44/1230 [01:19<32:09,  1.63s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 793.77it/s]
Season 2023-24:   4%|▉                        | 45/1230 [01:20<26:53,  1.36s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 703.10it/s]
Season 2023-24:   4%|▉                        | 46/1230 [01:20<21:03,  1.07s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 433.75it/s]
Season 2023-24:   4%|▉                        | 47/1230 [01:21<18:44,  1.05it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 417.27it/s]
Season 2023-24:   4%|▉                        | 48/1230 [01:21<15:11,  1.30it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 442.79it/s]
Season 2023-24:   4%|▉                        | 49/1230 [01:24<30:52,  1.57s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 553.09it/s]
Season 2023-24:   4%|█                        | 50/1230 [01:30<56:53,  2.89s/it]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 530.11it/s]

100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 430.64it/s]
Season 2023-24:   4%|█                        | 52/1230 [01:32<38:37,  1.97s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 627.26it/s]
Season 2023-24:   4%|█                        | 53/1230 [01:32<29:47,  1.52s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 345.14it/s]
Season 2023-24:   4%|█                        | 54/1230 [01:34<31:26,  1.60s/it]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 400.07it/s]
Season 2023-24:   4%|█                        | 55/1230 [01:35<24:42,  1.26s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 465.92it/s]
Season 2023-24:   5%|█▏                       | 56/1230 [01:35<19:50,  1.01s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 428.84it/s]
Season 2023-24:   5%|█▏                       | 57/1230 [01:37<24:07,  1.23s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 361.61it/s]
Season 2023-24:   5%|█▏                       | 58/1230 [01:40<35:35,  1.82s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 446.88it/s]
Season 2023-24:   5%|█▏                       | 59/1230 [01:43<44:00,  2.25s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 472.26it/s]
Season 2023-24:   5%|█▏                       | 60/1230 [01:46<43:55,  2.25s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 412.36it/s]
Season 2023-24:   5%|█▏                       | 61/1230 [01:47<38:50,  1.99s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 446.47it/s]
Season 2023-24:   5%|█▎                       | 62/1230 [01:48<33:54,  1.74s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 389.12it/s]
Season 2023-24:   5%|█▎                       | 63/1230 [01:53<52:53,  2.72s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 478.67it/s]
Season 2023-24:   5%|█▎                       | 64/1230 [01:55<48:04,  2.47s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 405.38it/s]
Season 2023-24:   5%|█▏                     | 65/1230 [02:01<1:07:23,  3.47s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 560.91it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 449.43it/s]
Season 2023-24:   6%|█▍                       | 69/1230 [02:07<46:38,  2.41s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 523.70it/s]
Season 2023-24:   6%|█▍                       | 70/1230 [02:09<47:12,  2.44s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 434.79it/s]
Season 2023-24:   6%|█▍                       | 71/1230 [02:13<51:56,  2.69s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 616.13it/s]
Season 2023-24:   6%|█▍                       | 72/1230 [02:13<38:12,  1.98s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 357.14it/s]
Season 2023-24:   6%|█▎                     | 73/1230 [02:22<1:16:09,  3.95s/it]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 728.06it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 436.23it/s]
Season 2023-24:   6%|█▌                       | 76/1230 [02:24<41:34,  2.16s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 360.91it/s]
Season 2023-24:   6%|█▌                       | 77/1230 [02:26<38:59,  2.03s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 455.56it/s]
Season 2023-24:   7%|█▋                       | 80/1230 [02:32<46:58,  2.45s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 406.51it/s]
Season 2023-24:   7%|█▋                       | 81/1230 [02:35<48:59,  2.56s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 481.11it/s]
Season 2023-24:   7%|█▋                       | 82/1230 [02:36<40:59,  2.14s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 459.26it/s]
Season 2023-24:   7%|█▋                       | 83/1230 [02:39<44:24,  2.32s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 450.78it/s]
Season 2023-24:   7%|█▋                       | 84/1230 [02:40<35:09,  1.84s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 351.35it/s]
Season 2023-24:   7%|█▋                       | 86/1230 [02:42<26:47,  1.40s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 373.78it/s]
Season 2023-24:   7%|█▊                       | 87/1230 [02:45<39:44,  2.09s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 462.92it/s]
Season 2023-24:   7%|█▊                       | 88/1230 [02:46<31:34,  1.66s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 446.17it/s]
Season 2023-24:   7%|█▊                       | 89/1230 [02:50<44:47,  2.36s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 463.11it/s]
Season 2023-24:   7%|█▊                       | 90/1230 [02:50<35:01,  1.84s/it]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 813.98it/s]
Season 2023-24:   7%|█▊                       | 91/1230 [02:52<34:58,  1.84s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 490.43it/s]
Season 2023-24:   7%|█▊                       | 92/1230 [02:53<30:27,  1.61s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 422.39it/s]
Season 2023-24:   8%|█▉                       | 94/1230 [02:57<36:41,  1.94s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 447.59it/s]
Season 2023-24:   8%|█▉                       | 95/1230 [02:59<31:41,  1.68s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 451.09it/s]


100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 622.10it/s]

100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 408.54it/s]
Season 2023-24:   8%|█▉                       | 98/1230 [03:03<26:23,  1.40s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 488.18it/s]
Season 2023-24:   8%|██                       | 99/1230 [03:06<33:37,  1.78s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 413.05it/s]
Season 2023-24:   8%|█▉                      | 100/1230 [03:07<29:28,  1.57s/it]
100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 373.93it/s]
Season 2023-24:   8%|█▉                      | 101/1230 [03:09<34:26,  1.83s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 446.56it/s]
Season 2023-24:   8%|█▉                      | 102/1230 [03:10<29:08,  1.55s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 431.64it/s]
Season 2023-24:   8%|██                      | 103/1230 [03:11<23:38,  1.26s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 459.88it/s]
Season 2023-24:   8%|██                      | 104/1230 [03:13<27:24,  1.46s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 468.55it/s]
Season 2023-24:   9%|██                      | 105/1230 [03:15<30:48,  1.64s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 408.63it/s]
Season 2023-24:   9%|██                      | 106/1230 [03:15<25:18,  1.35s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 466.61it/s]
Season 2023-24:   9%|██                      | 107/1230 [03:18<32:50,  1.75s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 443.58it/s]
Season 2023-24:   9%|██                      | 108/1230 [03:19<27:55,  1.49s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 464.81it/s]
Season 2023-24:   9%|██▏                     | 109/1230 [03:21<30:33,  1.64s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 433.93it/s]
Season 2023-24:   9%|██▏                     | 110/1230 [03:23<31:14,  1.67s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 861.64it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 664.47it/s]
Season 2023-24:   9%|██▏                     | 112/1230 [03:23<17:20,  1.07it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 404.77it/s]
Season 2023-24:   9%|██▏                     | 113/1230 [03:23<15:01,  1.24it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 409.67it/s]
Season 2023-24:   9%|██▏                     | 114/1230 [03:31<50:03,  2.69s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 635.10it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 474.92it/s]
Season 2023-24:   9%|██▎                     | 116/1230 [03:32<31:00,  1.67s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 426.26it/s]
Season 2023-24:  10%|██▎                     | 117/1230 [03:33<27:35,  1.49s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 519.77it/s]
Season 2023-24:  10%|██▎                     | 118/1230 [03:36<36:59,  2.00s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 445.83it/s]
Season 2023-24:  10%|██▎                     | 119/1230 [03:38<37:13,  2.01s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 852.15it/s]

100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 409.47it/s]
Season 2023-24:  10%|██▎                     | 121/1230 [03:42<36:56,  2.00s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 820.43it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 411.38it/s]
Season 2023-24:  10%|██▍                     | 124/1230 [03:44<23:37,  1.28s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 433.62it/s]
Season 2023-24:  10%|██▍                     | 125/1230 [03:46<26:17,  1.43s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 391.74it/s]
Season 2023-24:  10%|██▍                     | 126/1230 [03:47<21:37,  1.18s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 454.14it/s]
Season 2023-24:  10%|██▍                     | 127/1230 [03:47<19:14,  1.05s/it]
100%|██████████████████████████████████████████| 40/40 [00:00<00:00, 530.88it/s]
Season 2023-24:  10%|██▍                     | 128/1230 [03:48<19:39,  1.07s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 437.04it/s]
Season 2023-24:  11%|██▌                     | 130/1230 [03:53<26:31,  1.45s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 478.73it/s]
Season 2023-24:  11%|██▌                     | 131/1230 [03:54<26:24,  1.44s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 398.40it/s]
Season 2023-24:  11%|██▌                     | 132/1230 [03:55<22:32,  1.23s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 848.79it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 497.95it/s]
Season 2023-24:  11%|██▌                     | 134/1230 [03:55<14:12,  1.29it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 529.11it/s]
Season 2023-24:  11%|██▋                     | 135/1230 [03:57<18:50,  1.03s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 499.12it/s]
Season 2023-24:  11%|██▋                     | 136/1230 [03:58<17:40,  1.03it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 437.35it/s]
Season 2023-24:  11%|██▋                     | 137/1230 [04:02<29:59,  1.65s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 915.57it/s]
Season 2023-24:  11%|██▋                     | 138/1230 [04:05<36:40,  2.02s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 404.77it/s]
Season 2023-24:  11%|██▋                     | 139/1230 [04:06<31:27,  1.73s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 803.82it/s]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 829.11it/s]
Season 2023-24:  11%|██▊                     | 141/1230 [04:06<17:59,  1.01it/s]

[WARN] 208 games failed in 2023-24. Examples:
  - 0022300699: index 0 is out of bounds for axis 0 with size 0
  - 0022300088: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
  - 0022301050: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)
  - 0022300498: index 0 is out of bounds for axis 0 with size 0
  - 0022300923: index 0 is out of bounds for axis 0 with size 0

Now Running Season: 2024-25

Season 2024-25:   0%|                        | 1/1230 [00:13<4:35:59, 13.47s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 516.64it/s]
Season 2024-25:   0%|                        | 2/1230 [00:14<2:06:37,  6.19s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 804.72it/s]
Season 2024-25:   0%|                        | 3/1230 [00:14<1:10:22,  3.44s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 478.33it/s]
Season 2024-25:   0%|                          | 4/1230 [00:15<44:53,  2.20s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 516.99it/s]
Season 2024-25:   0%|                          | 5/1230 [00:15<32:42,  1.60s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 692.78it/s]
Season 2024-25:   0%|▏                         | 6/1230 [00:15<22:42,  1.11s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 378.24it/s]
Season 2024-25:   1%|▏                         | 7/1230 [00:17<25:56,  1.27s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 501.10it/s]
Season 2024-25:   1%|▏                         | 8/1230 [00:17<20:33,  1.01s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 392.76it/s]
Season 2024-25:   1%|▏                         | 9/1230 [00:24<57:22,  2.82s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 443.16it/s]
Season 2024-25:   1%|▏                        | 10/1230 [00:26<54:21,  2.67s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 737.19it/s]
Season 2024-25:   1%|▏                        | 11/1230 [00:27<38:38,  1.90s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 444.85it/s]
Season 2024-25:   1%|▏                        | 12/1230 [00:27<28:51,  1.42s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 537.13it/s]
Season 2024-25:   1%|▎                        | 13/1230 [00:28<27:56,  1.38s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 447.41it/s]
Season 2024-25:   1%|▎                        | 14/1230 [00:29<24:00,  1.18s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 805.17it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 483.09it/s]
Season 2024-25:   1%|▎                        | 16/1230 [00:29<14:40,  1.38it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 486.15it/s]
Season 2024-25:   1%|▎                        | 17/1230 [00:38<53:42,  2.66s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 534.58it/s]
Season 2024-25:   1%|▎                        | 18/1230 [00:42<59:20,  2.94s/it]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 437.10it/s]
Season 2024-25:   2%|▍                        | 19/1230 [00:42<45:25,  2.25s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 399.39it/s]
Season 2024-25:   2%|▍                        | 20/1230 [00:43<37:10,  1.84s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 514.88it/s]
Season 2024-25:   2%|▍                        | 22/1230 [00:45<31:32,  1.57s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 393.75it/s]
Season 2024-25:   2%|▍                        | 23/1230 [00:48<37:22,  1.86s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 811.21it/s]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 386.98it/s]
Season 2024-25:   2%|▌                        | 25/1230 [00:55<53:10,  2.65s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 425.22it/s]
Season 2024-25:   2%|▍                      | 26/1230 [01:00<1:03:43,  3.18s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 511.23it/s]
Season 2024-25:   2%|▌                        | 27/1230 [01:00<49:03,  2.45s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 834.48it/s]

100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 486.12it/s]
Season 2024-25:   2%|▌                        | 29/1230 [01:02<36:07,  1.80s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 780.25it/s]

  0%|                                                    | 0/45 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 45/45 [00:00<00:00, 442.29it/s]
Season 2024-25:   3%|▋                        | 31/1230 [01:06<37:00,  1.85s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 722.97it/s]
Season 2024-25:   3%|▋                        | 32/1230 [01:07<36:26,  1.82s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 477.67it/s]
Season 2024-25:   3%|▋                        | 34/1230 [01:12<44:49,  2.25s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 492.42it/s]
Season 2024-25:   3%|▋                        | 35/1230 [01:13<36:31,  1.83s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 745.10it/s]
Season 2024-25:   3%|▋                        | 36/1230 [01:15<37:03,  1.86s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 468.34it/s]
Season 2024-25:   3%|▊                        | 37/1230 [01:16<32:22,  1.63s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 511.32it/s]
Season 2024-25:   3%|▊                        | 38/1230 [01:20<43:09,  2.17s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 458.69it/s]
Season 2024-25:   3%|▊                        | 39/1230 [01:22<42:11,  2.13s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 761.89it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 472.64it/s]
Season 2024-25:   3%|▊                        | 41/1230 [01:24<34:57,  1.76s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 487.57it/s]
Season 2024-25:   3%|▊                        | 42/1230 [01:27<38:37,  1.95s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 477.78it/s]
Season 2024-25:   3%|▊                        | 43/1230 [01:28<34:58,  1.77s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 360.95it/s]
Season 2024-25:   4%|▉                        | 44/1230 [01:32<44:23,  2.25s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 769.21it/s]

  0%|                                                    | 0/47 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 47/47 [00:00<00:00, 431.56it/s]
Season 2024-25:   4%|▉                        | 46/1230 [01:35<37:37,  1.91s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 762.03it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 376.75it/s]
Season 2024-25:   4%|▉                        | 48/1230 [01:36<30:07,  1.53s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 433.84it/s]
Season 2024-25:   4%|▉                        | 49/1230 [01:40<38:42,  1.97s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 500.15it/s]
Season 2024-25:   4%|█                        | 50/1230 [01:41<33:11,  1.69s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 420.57it/s]
Season 2024-25:   4%|█                        | 52/1230 [01:49<56:46,  2.89s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 754.76it/s]

100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 473.19it/s]
Season 2024-25:   4%|█                        | 54/1230 [01:49<34:27,  1.76s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 533.98it/s]
Season 2024-25:   4%|█                        | 55/1230 [01:50<27:37,  1.41s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 424.84it/s]
Season 2024-25:   5%|█▏                       | 56/1230 [01:51<28:04,  1.43s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 407.94it/s]
Season 2024-25:   5%|█▏                       | 57/1230 [01:56<45:56,  2.35s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 579.84it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 389.31it/s]
Season 2024-25:   5%|█▏                       | 59/1230 [02:01<46:17,  2.37s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 428.84it/s]
Season 2024-25:   5%|█▏                       | 60/1230 [02:04<51:29,  2.64s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 478.80it/s]
Season 2024-25:   5%|█▏                       | 61/1230 [02:05<40:00,  2.05s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 438.91it/s]
Season 2024-25:   5%|█▎                       | 62/1230 [02:07<40:38,  2.09s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 765.72it/s]
Season 2024-25:   5%|█▎                       | 63/1230 [02:07<30:25,  1.56s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 378.88it/s]
Season 2024-25:   5%|█▎                       | 64/1230 [02:08<29:28,  1.52s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 834.63it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 463.29it/s]
Season 2024-25:   5%|█▎                       | 66/1230 [02:09<18:20,  1.06it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 362.83it/s]
Season 2024-25:   5%|█▎                       | 67/1230 [02:13<33:06,  1.71s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 409.11it/s]
Season 2024-25:   6%|█▍                       | 68/1230 [02:18<47:26,  2.45s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 424.03it/s]
Season 2024-25:   6%|█▍                       | 69/1230 [02:18<37:11,  1.92s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 361.94it/s]
Season 2024-25:   6%|█▍                       | 70/1230 [02:20<35:09,  1.82s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 604.11it/s]
Season 2024-25:   6%|█▍                       | 71/1230 [02:20<26:11,  1.36s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 474.49it/s]
Season 2024-25:   6%|█▍                       | 72/1230 [02:21<25:16,  1.31s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 525.16it/s]
Season 2024-25:   6%|█▍                       | 73/1230 [02:23<29:05,  1.51s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 501.12it/s]
Season 2024-25:   6%|█▌                       | 74/1230 [02:24<24:21,  1.26s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 451.88it/s]
Season 2024-25:   6%|█▌                       | 75/1230 [02:27<35:05,  1.82s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 491.07it/s]
Season 2024-25:   6%|█▌                       | 76/1230 [02:30<42:52,  2.23s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 486.11it/s]
Season 2024-25:   6%|█▌                       | 77/1230 [02:31<36:29,  1.90s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 507.08it/s]
Season 2024-25:   6%|█▌                       | 78/1230 [02:32<27:44,  1.44s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 524.90it/s]
Season 2024-25:   6%|█▌                       | 79/1230 [02:32<21:34,  1.12s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 486.32it/s]
Season 2024-25:   7%|█▋                       | 80/1230 [02:34<28:43,  1.50s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 503.67it/s]
Season 2024-25:   7%|█▋                       | 81/1230 [02:36<32:09,  1.68s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 484.74it/s]
Season 2024-25:   7%|█▋                       | 82/1230 [02:40<44:06,  2.30s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 625.77it/s]
Season 2024-25:   7%|█▋                       | 83/1230 [02:40<31:57,  1.67s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 542.74it/s]
Season 2024-25:   7%|█▋                       | 84/1230 [02:42<30:31,  1.60s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 464.90it/s]
Season 2024-25:   7%|█▋                       | 85/1230 [02:42<24:43,  1.30s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 483.73it/s]
Season 2024-25:   7%|█▋                       | 86/1230 [02:43<19:19,  1.01s/it]
100%|██████████████████████████████████████████| 40/40 [00:00<00:00, 547.01it/s]
Season 2024-25:   7%|█▊                       | 87/1230 [02:45<28:30,  1.50s/it]
100%|██████████████████████████████████████████| 19/19 [00:00<00:00, 418.85it/s]
Season 2024-25:   7%|█▊                       | 88/1230 [02:47<30:26,  1.60s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 804.52it/s]
Season 2024-25:   7%|█▊                       | 89/1230 [02:47<21:57,  1.15s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 572.48it/s]
Season 2024-25:   7%|█▊                       | 90/1230 [02:51<34:00,  1.79s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 526.77it/s]
Season 2024-25:   7%|█▊                       | 91/1230 [02:51<26:01,  1.37s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 644.30it/s]
Season 2024-25:   7%|█▊                       | 92/1230 [02:51<18:46,  1.01it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 727.74it/s]
Season 2024-25:   8%|█▉                       | 93/1230 [02:51<14:28,  1.31it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 427.49it/s]
Season 2024-25:   8%|█▉                       | 94/1230 [02:57<43:56,  2.32s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 826.57it/s]

100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 486.26it/s]
Season 2024-25:   8%|█▉                       | 96/1230 [03:00<33:34,  1.78s/it]
100%|██████████████████████████████████████████| 40/40 [00:00<00:00, 534.34it/s]
Season 2024-25:   8%|█▉                       | 97/1230 [03:00<27:51,  1.48s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 331.00it/s]
Season 2024-25:   8%|█▉                       | 98/1230 [03:04<41:05,  2.18s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 608.84it/s]
Season 2024-25:   8%|██                       | 99/1230 [03:05<31:12,  1.66s/it]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 452.07it/s]
Season 2024-25:   8%|█▉                      | 100/1230 [03:05<24:54,  1.32s/it]
100%|██████████████████████████████████████████| 39/39 [00:00<00:00, 579.91it/s]
Season 2024-25:   8%|█▉                      | 101/1230 [03:06<22:28,  1.19s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 498.54it/s]
Season 2024-25:   8%|█▉                      | 102/1230 [03:09<33:25,  1.78s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 500.75it/s]
Season 2024-25:   8%|██                      | 103/1230 [03:12<38:15,  2.04s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 615.44it/s]
Season 2024-25:   8%|██                      | 104/1230 [03:12<28:08,  1.50s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 420.10it/s]
Season 2024-25:   9%|██                      | 105/1230 [03:14<32:12,  1.72s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 438.14it/s]
Season 2024-25:   9%|██                      | 106/1230 [03:16<32:24,  1.73s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 464.59it/s]
Season 2024-25:   9%|██                      | 107/1230 [03:17<26:41,  1.43s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 544.70it/s]
Season 2024-25:   9%|██                      | 108/1230 [03:19<30:29,  1.63s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 456.54it/s]
Season 2024-25:   9%|██▏                     | 109/1230 [03:21<34:48,  1.86s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 601.85it/s]
Season 2024-25:   9%|██▏                     | 110/1230 [03:21<25:24,  1.36s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 557.99it/s]
Season 2024-25:   9%|██▏                     | 111/1230 [03:23<26:32,  1.42s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 483.95it/s]
Season 2024-25:   9%|██▏                     | 112/1230 [03:25<30:49,  1.65s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 386.13it/s]
Season 2024-25:   9%|██▏                     | 113/1230 [03:29<43:34,  2.34s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 558.94it/s]


100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 842.86it/s]

100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 510.59it/s]
Season 2024-25:   9%|██▎                     | 116/1230 [03:35<40:51,  2.20s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 393.46it/s]
Season 2024-25:  10%|██▎                     | 117/1230 [03:36<37:04,  2.00s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 408.04it/s]
Season 2024-25:  10%|██▎                     | 118/1230 [03:38<34:42,  1.87s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 450.54it/s]
Season 2024-25:  10%|██▎                     | 119/1230 [03:38<26:53,  1.45s/it]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 849.01it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 555.97it/s]
Season 2024-25:  10%|██▎                     | 121/1230 [03:42<31:09,  1.69s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 471.61it/s]
Season 2024-25:  10%|██▍                     | 122/1230 [03:44<30:48,  1.67s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 527.29it/s]
Season 2024-25:  10%|██▍                     | 123/1230 [03:44<26:50,  1.45s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 379.93it/s]
Season 2024-25:  10%|██▍                     | 124/1230 [03:49<42:31,  2.31s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 377.33it/s]
Season 2024-25:  10%|██▍                     | 125/1230 [03:50<34:39,  1.88s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 517.10it/s]
Season 2024-25:  10%|██▍                     | 126/1230 [03:51<32:51,  1.79s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 520.73it/s]
Season 2024-25:  10%|██▍                     | 127/1230 [03:53<32:52,  1.79s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 459.33it/s]
Season 2024-25:  10%|██▍                     | 128/1230 [03:55<33:25,  1.82s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 616.13it/s]
Season 2024-25:  10%|██▌                     | 129/1230 [03:58<36:51,  2.01s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 433.81it/s]
Season 2024-25:  11%|██▌                     | 130/1230 [03:59<31:13,  1.70s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 457.40it/s]
Season 2024-25:  11%|██▌                     | 131/1230 [04:00<32:22,  1.77s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 489.54it/s]
Season 2024-25:  11%|██▌                     | 132/1230 [04:02<29:07,  1.59s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 470.99it/s]

[WARN] 1012 games failed in 2024-25. Examples:
  - 0022401011: index 0 is out of bounds for axis 0 with size 0
  - 0022400223: index 0 is out of bounds for axis 0 with size 0
  - 0022400290: index 0 is out of bounds for axis 0 with size 0
  - 0022400390: index 0 is out of bounds for axis 0 with size 0
  - 0022401069: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

## Save the Failed Games to a .pkl File

In [51]:
import pickle

with open("failed_games.pkl", "wb") as file:
    pickle.dump(all_failed_games, file)

## Save the Pulled Data to a .CSV File

In [53]:
final_df.to_csv("stint_wise_data.csv", index = False)

# Load the Failed Games .pkl File and Rerun the Scraping

In [73]:
failed_games_df = pd.DataFrame(columns = ['SEASON', 'GAME_ID', 'STINT_START_TIME', 'STINT_END_TIME', 'PT_DIFF'])

In [75]:
import pickle

# Replace with the path to the latest failed games .pkl file
# Use 'failed_games_2025-11-30.pkl' for next Run
file_path = 'failed_games.pkl' 

with open(file_path, 'rb') as file:
    all_failed_games = pickle.load(file)

all_failed_games

{'2022-23': [('0022200039',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200497',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201167',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201072',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200869',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200281',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200793',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200426',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200969',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200892',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200397',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022201194',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200918',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201050',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200499',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200749',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200328',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201205',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201052',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200107',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200356',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200561',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200902',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200395',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200082',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200782',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200009',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200169',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200652',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200519',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200854',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200765',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200626',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200567',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200569',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200901',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200027',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200040',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200659',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200225',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200274',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200418',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200063',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200363',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200134',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200679',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200730',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200795',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201051',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200033',
   requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError('None: Max retries exceeded with url: /stats/gamerotation?GameID=0022200033&LeagueID=00 (Caused by None)'))),
  ('0022200956',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200184',
   requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError('None: Max retries exceeded with url: /stats/gamerotation?GameID=0022200184&LeagueID=00 (Caused by None)'))),
  ('0022200774',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200817',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200630',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200440',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200357',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200400',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200072',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201120',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200478',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022201007',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200224',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201186',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200971',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200550',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022201094',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200024',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022201012',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200099',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200382',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200758',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200948',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200462',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200748',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200993',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200848',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200558',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200453',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200962',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200472',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200835',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200414',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200174',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200058',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200887',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200268',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200066',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200552',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200086',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200235',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200401',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200917',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200010',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200930',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200132',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200767',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200113',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022200076',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022201001',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200168',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201161',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022200488',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200512',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022201040',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200117',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200101',
   requests.exceptions.ConnectionError(urllib3.exceptions.ProtocolError('Connection aborted.',
                                                                        http.client.RemoteDisconnected('Remote end closed connection without response')))),
  ('0022200325',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200025',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200786',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022201170',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200413',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022200800',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)'))],
 '2023-24': [('0022300699',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300088',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301050',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300498',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300923',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301099',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300523',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300506',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300856',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301045',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300623',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300741',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300162',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300981',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300029',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300642',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300522',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300132',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300007',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300604',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300618',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300862',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300082',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300100',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300127',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300167',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300188',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301086',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300170',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300517',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300349',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300040',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300552',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301117',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300300',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300499',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300362',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301131',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300521',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300407',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300670',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300410',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301147',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300474',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300562',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300083',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300598',
   json.decoder.JSONDecodeError('Expecting value: line 1 column 1 (char 0)')),
  ('0022301222',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300752',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300710',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300520',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300982',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300707',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300266',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300397',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300454',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300944',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301070',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300289',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300723',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301060',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022301190',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300269',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300911',
   IndexError('index 0 is out of bounds for axis 0 with size 0')),
  ('0022300822',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300560',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300179',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300738',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300032',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300928',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300557',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300653',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300094',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300715',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300947',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300422',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301068',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300021',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301014',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300948',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300378',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300838',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301195',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301078',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300098',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300141',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300058',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300416',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300826',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301026',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300161',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300525',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300471',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300488',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300555',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022301043',
   requests.exceptions.ReadTimeout(urllib3.exceptions.ReadTimeoutError('None: None'))),
  ('0022300011',
   requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError('None: Max retries exceeded with url: /stats/gamerotation?GameID=0022300011&LeagueID=00 (Caused by None)'))),
  ('0022300534',

In [77]:
all_failed_games.keys()

dict_keys(['2022-23', '2023-24', '2024-25'])

In [79]:
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
import time
import warnings
warnings.filterwarnings("ignore")

# Tune this based on your API limits / machine
MAX_WORKERS = 8

failed_games_df_list = []  # collect per-season concatenations here
new_failed_games = {} # Record any new failed games here

for szn in all_failed_games.keys():
    print(f"\nNow Running Season: {szn}")

    game_ids = [item[0] for item in all_failed_games[szn]] #Grab the list of Game IDs of the failed Games.
        
    time.sleep(5) #Sleep for 5 seconds after first API call for Game Log for a Season

    season_frames = []
    failures = []

    # Parallelize over games in this season
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futures = {ex.submit(process_game, gid, szn): gid for gid in game_ids}

        # Progress bar advances as futures complete (order-agnostic)
        for fut in tqdm(as_completed(futures), total=len(futures), desc=f"Season {szn}"):
            gid = futures[fut]
            try:
                season_frames.append(fut.result())
            except Exception as e:
                failures.append((gid, e))

    # Concatenate once per season for speed
    if season_frames:
        season_df = pd.concat(season_frames, axis=0, ignore_index=True)
        failed_games_df_list.append(season_df)

    if failures:
        # Log Failures
        print(f"[WARN] {len(failures)} games failed in {szn}. Examples:")
        for gid, err in failures[:5]:
            print(f"  - {gid}: {err}")

        #Log Failures
        new_failed_games[szn] = failures

    # If you still want a short pause between seasons, keep this:
    time.sleep(5)

# Single concat at the very end
failed_games_df = pd.concat(failed_games_df_list, axis=0, ignore_index=True)

Now Running Season: 2022-23

Season 2022-23:   4%|▉                          | 4/113 [00:11<03:13,  1.77s/it]
100%|██████████████████████████████████████████| 39/39 [00:00<00:00, 481.25it/s]
Season 2022-23:   8%|██▏                        | 9/113 [00:16<02:11,  1.27s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 452.55it/s]
Season 2022-23:  19%|████▊                     | 21/113 [00:32<01:14,  1.24it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 484.17it/s]
Season 2022-23:  23%|█████▉                    | 26/113 [00:38<02:04,  1.43s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 427.88it/s]
Season 2022-23:  27%|███████▏                  | 31/113 [00:46<01:55,  1.40s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 550.34it/s]
Season 2022-23:  30%|███████▊                  | 34/113 [00:52<02:08,  1.63s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 771.35it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 419.80it/s]
Season 2022-23:  39%|██████████                | 44/113 [01:01<00:52,  1.31it/s]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 397.32it/s]
Season 2022-23:  41%|██████████▌               | 46/113 [01:06<01:32,  1.37s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 491.18it/s]
Season 2022-23:  42%|███████████               | 48/113 [01:08<01:12,  1.12s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 459.62it/s]
Season 2022-23:  45%|███████████▋              | 51/113 [01:11<01:09,  1.12s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 397.31it/s]
Season 2022-23:  49%|████████████▋             | 55/113 [01:18<01:35,  1.65s/it]
100%|██████████████████████████████████████████| 45/45 [00:00<00:00, 482.80it/s]
Season 2022-23:  50%|████████████▉             | 56/113 [01:19<01:12,  1.27s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 353.61it/s]
Season 2022-23:  50%|█████████████             | 57/113 [01:21<01:33,  1.67s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 846.16it/s]
Season 2022-23:  52%|█████████████▌            | 59/113 [01:23<01:11,  1.32s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 452.41it/s]
Season 2022-23:  57%|██████████████▋           | 64/113 [01:31<01:00,  1.24s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 429.60it/s]
Season 2022-23:  58%|██████████████▉           | 65/113 [01:31<00:47,  1.00it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 400.39it/s]
Season 2022-23:  59%|███████████████▍          | 67/113 [01:32<00:35,  1.28it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 459.53it/s]
Season 2022-23:  62%|████████████████          | 70/113 [01:45<02:00,  2.79s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 358.90it/s]
Season 2022-23:  64%|████████████████▌         | 72/113 [01:47<01:18,  1.91s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 438.18it/s]
Season 2022-23:  65%|█████████████████         | 74/113 [01:48<00:49,  1.27s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 414.21it/s]
Season 2022-23:  70%|██████████████████▏       | 79/113 [02:03<01:20,  2.38s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 406.05it/s]
Season 2022-23:  73%|███████████████████       | 83/113 [02:16<01:10,  2.35s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 432.60it/s]
Season 2022-23:  75%|███████████████████▌      | 85/113 [02:18<00:50,  1.81s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 466.17it/s]
Season 2022-23:  80%|████████████████████▋     | 90/113 [02:37<00:54,  2.37s/it]
  0%|                                                    | 0/41 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 41/41 [00:00<00:00, 407.07it/s]
Season 2022-23:  81%|████████████████████▉     | 91/113 [02:42<01:07,  3.07s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 463.38it/s]
Season 2022-23:  81%|█████████████████████▏    | 92/113 [02:43<00:53,  2.55s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 480.59it/s]
Season 2022-23:  84%|█████████████████████▊    | 95/113 [02:46<00:24,  1.35s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 624.43it/s]
Season 2022-23:  86%|██████████████████████▎   | 97/113 [02:46<00:12,  1.29it/s]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 383.98it/s]
Season 2022-23:  95%|███████████████████████▋ | 107/113 [03:02<00:07,  1.28s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 478.73it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 447.55it/s]
Season 2022-23:  96%|████████████████████████ | 109/113 [03:02<00:03,  1.09it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 424.17it/s]
Season 2022-23:  99%|████████████████████████▊| 112/113 [03:06<00:01,  1.07s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 463.81it/s]
Season 2022-23: 100%|█████████████████████████| 113/113 [03:12<00:00,  1.70s/it]

[WARN] 80 games failed in 2022-23. Examples:
  - 0022200869: index 0 is out of bounds for axis 0 with size 0
  - 0022201072: index 0 is out of bounds for axis 0 with size 0
  - 0022200281: index 0 is out of bounds for axis 0 with size 0
  - 0022200426: index 0 is out of bounds for axis 0 with size 0
  - 0022201167: index 0 is out of bounds for axis 0 with size 0

Now Running Season: 2023-24

Season 2023-24:   2%|▌                          | 4/208 [00:08<05:30,  1.62s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 480.62it/s]
Season 2023-24:   3%|▊                          | 6/208 [00:09<03:18,  1.02it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 577.44it/s]
Season 2023-24:   7%|█▊                        | 14/208 [00:19<03:38,  1.13s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 460.25it/s]
Season 2023-24:   7%|█▊                        | 15/208 [00:20<03:27,  1.08s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 430.61it/s]
Season 2023-24:   8%|██▏                       | 17/208 [00:23<04:08,  1.30s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 542.74it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 680.89it/s]
Season 2023-24:   9%|██▍                       | 19/208 [00:23<02:24,  1.31it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 401.21it/s]
Season 2023-24:  10%|██▋                       | 21/208 [00:27<03:22,  1.08s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 431.65it/s]
Season 2023-24:  12%|███                       | 24/208 [00:33<05:52,  1.91s/it]
100%|██████████████████████████████████████████| 39/39 [00:00<00:00, 544.92it/s]
Season 2023-24:  12%|███▏                      | 25/208 [00:33<04:31,  1.48s/it]
100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 864.07it/s]
Season 2023-24:  14%|███▋                      | 29/208 [00:36<02:52,  1.04it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 429.93it/s]
Season 2023-24:  17%|████▌                     | 36/208 [00:45<02:45,  1.04it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 539.77it/s]
Season 2023-24:  19%|████▉                     | 39/208 [00:46<01:30,  1.86it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 402.93it/s]
Season 2023-24:  21%|█████▌                    | 44/208 [00:56<04:05,  1.49s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 453.07it/s]
Season 2023-24:  23%|██████                    | 48/208 [01:02<04:33,  1.71s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 476.60it/s]
Season 2023-24:  25%|██████▍                   | 51/208 [01:02<02:07,  1.23it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 436.06it/s]
Season 2023-24:  25%|██████▌                   | 52/208 [01:03<02:16,  1.14it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 375.91it/s]
Season 2023-24:  25%|██████▋                   | 53/208 [01:05<03:07,  1.21s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 423.77it/s]
Season 2023-24:  26%|██████▊                   | 54/208 [01:06<02:32,  1.01it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 398.28it/s]
Season 2023-24:  27%|███████                   | 56/208 [01:10<03:20,  1.32s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 428.35it/s]
Season 2023-24:  28%|███████▍                  | 59/208 [01:13<02:51,  1.15s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 359.84it/s]
Season 2023-24:  31%|████████                  | 64/208 [01:21<02:53,  1.20s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 476.83it/s]
Season 2023-24:  31%|████████▏                 | 65/208 [01:22<02:32,  1.07s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 471.25it/s]
Season 2023-24:  32%|████████▎                 | 66/208 [01:23<02:22,  1.00s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 420.41it/s]
Season 2023-24:  32%|████████▍                 | 67/208 [01:27<04:34,  1.95s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 456.84it/s]
Season 2023-24:  33%|████████▌                 | 68/208 [01:30<04:49,  2.07s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 441.78it/s]
Season 2023-24:  33%|████████▋                 | 69/208 [01:32<05:03,  2.18s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 533.42it/s]
Season 2023-24:  34%|████████▊                 | 70/208 [01:34<04:32,  1.98s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 493.65it/s]

100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 381.75it/s]
Season 2023-24:  35%|█████████                 | 72/208 [01:34<02:46,  1.23s/it]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 861.79it/s]

100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 399.10it/s]
Season 2023-24:  36%|█████████▎                | 74/208 [01:37<03:06,  1.39s/it]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 778.28it/s]

100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 573.28it/s]
Season 2023-24:  37%|█████████▌                | 76/208 [01:41<03:22,  1.53s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 651.90it/s]
Season 2023-24:  38%|█████████▊                | 78/208 [01:43<02:53,  1.33s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 473.84it/s]
Season 2023-24:  38%|█████████▉                | 79/208 [01:44<02:27,  1.14s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 490.71it/s]
Season 2023-24:  38%|██████████                | 80/208 [01:45<02:29,  1.17s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 418.92it/s]
Season 2023-24:  39%|██████████▏               | 81/208 [01:47<02:41,  1.27s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 424.08it/s]
Season 2023-24:  39%|██████████▎               | 82/208 [01:50<03:36,  1.72s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 828.07it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 657.77it/s]
Season 2023-24:  41%|██████████▋               | 85/208 [01:51<02:06,  1.03s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 454.23it/s]
Season 2023-24:  41%|██████████▊               | 86/208 [01:52<01:47,  1.14it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 555.55it/s]
Season 2023-24:  42%|██████████▉               | 87/208 [01:52<01:25,  1.42it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 352.10it/s]
Season 2023-24:  42%|███████████               | 88/208 [01:55<02:54,  1.46s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 836.66it/s]
Season 2023-24:  43%|███████████▏              | 89/208 [01:55<02:07,  1.07s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 405.76it/s]
Season 2023-24:  43%|███████████▎              | 90/208 [01:58<03:06,  1.58s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 408.11it/s]
Season 2023-24:  44%|███████████▍              | 91/208 [01:59<02:36,  1.34s/it]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 867.85it/s]

100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 534.51it/s]
Season 2023-24:  45%|███████████▋              | 93/208 [01:59<01:33,  1.23it/s]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 402.37it/s]
Season 2023-24:  45%|███████████▊              | 94/208 [02:00<01:34,  1.21it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 440.72it/s]
Season 2023-24:  46%|███████████▉              | 95/208 [02:01<01:20,  1.40it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 464.56it/s]
Season 2023-24:  46%|████████████              | 96/208 [02:03<02:21,  1.26s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 498.48it/s]
Season 2023-24:  47%|████████████▏             | 97/208 [02:06<02:57,  1.60s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 409.21it/s]
Season 2023-24:  47%|████████████▎             | 98/208 [02:08<03:03,  1.67s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 766.44it/s]
Season 2023-24:  48%|████████████▍             | 99/208 [02:08<02:14,  1.23s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 479.36it/s]
Season 2023-24:  48%|████████████             | 100/208 [02:09<02:04,  1.15s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 462.57it/s]
Season 2023-24:  49%|████████████▏            | 101/208 [02:13<03:52,  2.17s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 603.82it/s]
Season 2023-24:  49%|████████████▎            | 102/208 [02:14<02:49,  1.60s/it]
100%|██████████████████████████████████████████| 40/40 [00:00<00:00, 629.71it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 436.21it/s]
Season 2023-24:  50%|████████████▌            | 104/208 [02:15<02:08,  1.23s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 402.59it/s]
Season 2023-24:  50%|████████████▌            | 105/208 [02:16<01:43,  1.00s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 414.24it/s]
Season 2023-24:  51%|████████████▋            | 106/208 [02:18<02:13,  1.31s/it]
100%|██████████████████████████████████████████| 20/20 [00:00<00:00, 363.25it/s]
Season 2023-24:  51%|████████████▊            | 107/208 [02:18<01:46,  1.05s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 770.98it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 434.71it/s]
Season 2023-24:  52%|█████████████            | 109/208 [02:24<03:14,  1.96s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 428.80it/s]
Season 2023-24:  53%|█████████████▏           | 110/208 [02:25<02:42,  1.66s/it]
100%|██████████████████████████████████████████| 19/19 [00:00<00:00, 744.72it/s]
Season 2023-24:  53%|█████████████▎           | 111/208 [02:26<02:19,  1.44s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 452.99it/s]
Season 2023-24:  54%|█████████████▍           | 112/208 [02:27<02:08,  1.34s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 488.26it/s]
Season 2023-24:  54%|█████████████▌           | 113/208 [02:27<01:43,  1.08s/it]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 791.66it/s]

100%|██████████████████████████████████████████| 19/19 [00:00<00:00, 369.01it/s]
Season 2023-24:  55%|█████████████▊           | 115/208 [02:32<02:41,  1.73s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 420.75it/s]
Season 2023-24:  56%|█████████████▉           | 116/208 [02:34<02:45,  1.80s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 425.98it/s]
Season 2023-24:  56%|██████████████           | 117/208 [02:37<02:50,  1.87s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 416.51it/s]
Season 2023-24:  57%|██████████████▏          | 118/208 [02:37<02:15,  1.51s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 476.94it/s]
Season 2023-24:  57%|██████████████▎          | 119/208 [02:44<04:30,  3.04s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 381.88it/s]
Season 2023-24:  58%|██████████████▍          | 120/208 [02:50<05:26,  3.71s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 797.66it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 821.69it/s]
Season 2023-24:  59%|██████████████▋          | 122/208 [02:50<02:58,  2.08s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 459.49it/s]
Season 2023-24:  59%|██████████████▊          | 123/208 [02:51<02:36,  1.85s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 463.48it/s]
Season 2023-24:  60%|██████████████▉          | 124/208 [02:51<02:11,  1.56s/it]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 402.65it/s]
Season 2023-24:  60%|███████████████          | 125/208 [02:56<03:04,  2.22s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 425.45it/s]
Season 2023-24:  61%|███████████████▎         | 127/208 [03:14<07:58,  5.91s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 510.96it/s]
Season 2023-24:  62%|███████████████▍         | 128/208 [03:14<05:39,  4.25s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 510.60it/s]
Season 2023-24:  64%|███████████████▉         | 133/208 [03:21<02:14,  1.79s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 467.18it/s]
Season 2023-24:  65%|████████████████▏        | 135/208 [03:26<02:28,  2.04s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 527.53it/s]
Season 2023-24:  65%|████████████████▎        | 136/208 [03:28<02:44,  2.29s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 394.00it/s]
Season 2023-24:  66%|████████████████▍        | 137/208 [03:35<04:07,  3.49s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 416.21it/s]
Season 2023-24:  66%|████████████████▌        | 138/208 [03:39<04:15,  3.65s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 381.21it/s]
Season 2023-24:  67%|████████████████▋        | 139/208 [03:43<04:16,  3.72s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 417.82it/s]
Season 2023-24:  69%|█████████████████▏       | 143/208 [03:50<02:51,  2.63s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 464.75it/s]
Season 2023-24:  70%|█████████████████▍       | 145/208 [03:58<03:25,  3.26s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 488.53it/s]
Season 2023-24:  70%|█████████████████▌       | 146/208 [03:58<02:38,  2.56s/it]
  0%|                                                    | 0/23 [00:00<?, ?it/s]

100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 774.29it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 277.68it/s]
Season 2023-24:  71%|█████████████████▋       | 147/208 [03:58<02:01,  2.00s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 404.16it/s]
Season 2023-24:  72%|█████████████████▉       | 149/208 [04:00<01:26,  1.47s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 457.78it/s]
Season 2023-24:  72%|██████████████████       | 150/208 [04:02<01:38,  1.70s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 463.78it/s]
Season 2023-24:  73%|██████████████████▏      | 151/208 [04:03<01:21,  1.43s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 650.93it/s]
Season 2023-24:  73%|██████████████████▎      | 152/208 [04:03<01:00,  1.09s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 341.55it/s]
Season 2023-24:  74%|██████████████████▍      | 153/208 [04:11<02:35,  2.83s/it]
  0%|                                                    | 0/26 [00:00<?, ?it/s]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 823.38it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 375.85it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 443.12it/s]
Season 2023-24:  75%|██████████████████▊      | 156/208 [04:11<01:15,  1.45s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 415.97it/s]
Season 2023-24:  75%|██████████████████▊      | 157/208 [04:12<01:06,  1.31s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 429.87it/s]
Season 2023-24:  76%|██████████████████▉      | 158/208 [04:13<01:03,  1.27s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 824.49it/s]
Season 2023-24:  76%|███████████████████      | 159/208 [04:13<00:48,  1.02it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 460.62it/s]
Season 2023-24:  77%|███████████████████▏     | 160/208 [04:16<01:07,  1.40s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 397.45it/s]
Season 2023-24:  77%|███████████████████▎     | 161/208 [04:21<01:46,  2.26s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 360.66it/s]
Season 2023-24:  78%|███████████████████▍     | 162/208 [04:21<01:25,  1.86s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 372.27it/s]
Season 2023-24:  78%|███████████████████▌     | 163/208 [04:23<01:14,  1.66s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 421.01it/s]
Season 2023-24:  79%|███████████████████▋     | 164/208 [04:24<01:14,  1.69s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 492.22it/s]
Season 2023-24:  79%|███████████████████▊     | 165/208 [04:25<00:58,  1.35s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 805.92it/s]
Season 2023-24:  80%|████████████████████     | 167/208 [04:26<00:36,  1.11it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 558.52it/s]
Season 2023-24:  81%|████████████████████▏    | 168/208 [04:27<00:39,  1.00it/s]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 453.40it/s]
Season 2023-24:  81%|████████████████████▎    | 169/208 [04:31<01:11,  1.84s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 658.20it/s]
Season 2023-24:  82%|████████████████████▍    | 170/208 [04:33<01:10,  1.85s/it]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 387.83it/s]
Season 2023-24:  82%|████████████████████▌    | 171/208 [04:34<00:59,  1.62s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 750.17it/s]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 386.92it/s]
Season 2023-24:  83%|████████████████████▊    | 173/208 [04:36<00:48,  1.40s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 409.19it/s]
Season 2023-24:  84%|████████████████████▉    | 174/208 [04:40<01:02,  1.85s/it]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 869.03it/s]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 411.10it/s]
Season 2023-24:  86%|█████████████████████▍   | 178/208 [04:42<00:33,  1.13s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 465.26it/s]
Season 2023-24:  87%|█████████████████████▊   | 181/208 [04:45<00:25,  1.05it/s]
100%|██████████████████████████████████████████| 23/23 [00:00<00:00, 405.00it/s]
Season 2023-24:  88%|█████████████████████▉   | 182/208 [04:50<00:52,  2.02s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 464.69it/s]
Season 2023-24:  88%|█████████████████████▉   | 183/208 [04:52<00:52,  2.09s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 450.64it/s]
Season 2023-24:  88%|██████████████████████   | 184/208 [04:54<00:47,  1.96s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 390.01it/s]
Season 2023-24:  89%|██████████████████████▏  | 185/208 [04:54<00:35,  1.53s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 826.32it/s]

100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 410.62it/s]
Season 2023-24:  90%|██████████████████████▍  | 187/208 [04:55<00:20,  1.01it/s]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 403.13it/s]
Season 2023-24:  90%|██████████████████████▌  | 188/208 [04:56<00:19,  1.05it/s]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 465.85it/s]
Season 2023-24:  91%|██████████████████████▋  | 189/208 [04:57<00:18,  1.00it/s]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 434.52it/s]

[WARN] 67 games failed in 2023-24. Examples:
  - 0022300506: index 0 is out of bounds for axis 0 with size 0
  - 0022300923: index 0 is out of bounds for axis 0 with size 0
  - 0022301050: index 0 is out of bounds for axis 0 with size 0
  - 0022300699: index 0 is out of bounds for axis 0 with size 0
  - 0022300498: index 0 is out of bounds for axis 0 with size 0

Now Running Season: 2024-25

Season 2024-25:   0%|▏                         | 5/1012 [00:11<23:02,  1.37s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 347.11it/s]
Season 2024-25:   1%|▏                         | 6/1012 [00:13<26:16,  1.57s/it]

100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 831.63it/s]

100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 466.27it/s]
Season 2024-25:   1%|▏                         | 8/1012 [00:14<16:39,  1.00it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 381.89it/s]
Season 2024-25:   1%|▎                        | 11/1012 [00:20<22:24,  1.34s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 840.41it/s]
Season 2024-25:   1%|▎                        | 12/1012 [00:22<24:21,  1.46s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 422.09it/s]
Season 2024-25:   1%|▎                        | 13/1012 [00:22<20:30,  1.23s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 472.84it/s]
Season 2024-25:   1%|▎                        | 14/1012 [00:23<16:28,  1.01it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 665.73it/s]
Season 2024-25:   1%|▎                        | 15/1012 [00:25<21:50,  1.31s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 463.92it/s]
Season 2024-25:   2%|▍                        | 16/1012 [00:26<20:13,  1.22s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 443.36it/s]
Season 2024-25:   2%|▍                        | 17/1012 [00:27<19:50,  1.20s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 479.95it/s]
Season 2024-25:   2%|▍                        | 18/1012 [00:29<24:49,  1.50s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 474.96it/s]
Season 2024-25:   2%|▍                        | 19/1012 [00:32<30:53,  1.87s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 428.91it/s]
Season 2024-25:   2%|▍                        | 20/1012 [00:33<30:10,  1.82s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 623.91it/s]
Season 2024-25:   2%|▌                        | 21/1012 [00:34<23:05,  1.40s/it]
100%|██████████████████████████████████████████| 46/46 [00:00<00:00, 583.95it/s]
Season 2024-25:   2%|▌                        | 22/1012 [00:34<18:25,  1.12s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 733.56it/s]
Season 2024-25:   2%|▌                        | 23/1012 [00:35<15:17,  1.08it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 357.46it/s]
Season 2024-25:   2%|▌                        | 24/1012 [00:35<12:48,  1.29it/s]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 488.87it/s]
Season 2024-25:   2%|▌                        | 25/1012 [00:36<11:58,  1.37it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 418.86it/s]
Season 2024-25:   3%|▋                        | 26/1012 [00:39<21:27,  1.31s/it]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 446.25it/s]
Season 2024-25:   3%|▋                        | 27/1012 [00:42<30:19,  1.85s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 422.50it/s]
Season 2024-25:   3%|▋                        | 28/1012 [00:43<30:07,  1.84s/it]
100%|██████████████████████████████████████████| 24/24 [00:00<00:00, 425.50it/s]
Season 2024-25:   3%|▋                        | 29/1012 [00:44<24:55,  1.52s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 816.28it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 722.80it/s]
Season 2024-25:   3%|▊                        | 32/1012 [00:45<11:45,  1.39it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 461.27it/s]
Season 2024-25:   3%|▊                        | 33/1012 [00:49<25:40,  1.57s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 606.61it/s]
Season 2024-25:   3%|▊                        | 34/1012 [00:53<33:10,  2.04s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 345.77it/s]
Season 2024-25:   3%|▊                        | 35/1012 [00:54<28:54,  1.78s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 710.85it/s]
Season 2024-25:   4%|▉                        | 36/1012 [00:57<34:25,  2.12s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 448.88it/s]
Season 2024-25:   4%|▉                        | 37/1012 [00:57<26:46,  1.65s/it]
100%|██████████████████████████████████████████| 41/41 [00:00<00:00, 794.21it/s]

100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 406.50it/s]
Season 2024-25:   4%|▉                        | 39/1012 [00:58<17:14,  1.06s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 483.97it/s]
Season 2024-25:   4%|▉                        | 40/1012 [01:01<24:21,  1.50s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 399.65it/s]
Season 2024-25:   4%|█                        | 41/1012 [01:03<25:10,  1.56s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 401.19it/s]
Season 2024-25:   4%|█                        | 42/1012 [01:04<24:47,  1.53s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 817.08it/s]
Season 2024-25:   4%|█                        | 44/1012 [01:11<38:52,  2.41s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 450.39it/s]
Season 2024-25:   4%|█                        | 45/1012 [01:12<31:16,  1.94s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 540.33it/s]
Season 2024-25:   5%|█▏                       | 46/1012 [01:12<24:26,  1.52s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 555.33it/s]
Season 2024-25:   5%|█▏                       | 47/1012 [01:12<19:00,  1.18s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 455.17it/s]
Season 2024-25:   5%|█▏                       | 48/1012 [01:12<15:15,  1.05it/s]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 363.78it/s]
Season 2024-25:   5%|█▏                       | 49/1012 [01:13<12:20,  1.30it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 462.14it/s]
Season 2024-25:   5%|█▏                       | 50/1012 [01:15<20:40,  1.29s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 578.41it/s]
Season 2024-25:   5%|█▎                       | 51/1012 [01:21<40:50,  2.55s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 782.93it/s]

100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 479.64it/s]
Season 2024-25:   5%|█▎                       | 53/1012 [01:22<25:39,  1.60s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 600.00it/s]
Season 2024-25:   5%|█▎                       | 55/1012 [01:24<19:51,  1.25s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 478.91it/s]
Season 2024-25:   6%|█▍                       | 56/1012 [01:24<16:22,  1.03s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 841.91it/s]

100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 751.36it/s]
Season 2024-25:   6%|█▍                       | 58/1012 [01:24<09:39,  1.65it/s]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 860.69it/s]
Season 2024-25:   6%|█▍                       | 59/1012 [01:32<38:36,  2.43s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 794.72it/s]
Season 2024-25:   6%|█▍                       | 60/1012 [01:34<32:51,  2.07s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 535.37it/s]

100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 436.97it/s]
Season 2024-25:   6%|█▌                       | 62/1012 [01:35<22:28,  1.42s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 440.51it/s]


Season 2024-25:   6%|█▌                       | 63/1012 [01:36<22:27,  1.42s/it]


100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 427.55it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 696.64it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 772.76it/s]
Season 2024-25:   7%|█▋                       | 66/1012 [01:36<11:38,  1.35it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 405.96it/s]
Season 2024-25:   7%|█▋                       | 67/1012 [01:46<39:53,  2.53s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 852.24it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 402.02it/s]
Season 2024-25:   7%|█▋                       | 69/1012 [01:47<28:49,  1.83s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 491.90it/s]
Season 2024-25:   7%|█▋                       | 70/1012 [01:48<25:24,  1.62s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 536.51it/s]
Season 2024-25:   7%|█▊                       | 71/1012 [01:48<20:55,  1.33s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 501.65it/s]
Season 2024-25:   7%|█▊                       | 72/1012 [01:51<25:29,  1.63s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 665.98it/s]
Season 2024-25:   7%|█▊                       | 73/1012 [01:51<19:46,  1.26s/it]
100%|██████████████████████████████████████████| 25/25 [00:00<00:00, 792.02it/s]

100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 427.59it/s]
Season 2024-25:   7%|█▊                       | 75/1012 [01:58<32:16,  2.07s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 762.17it/s]
Season 2024-25:   8%|█▉                       | 76/1012 [01:58<26:16,  1.68s/it]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 382.52it/s]
Season 2024-25:   8%|█▉                       | 77/1012 [01:59<22:36,  1.45s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 489.09it/s]
Season 2024-25:   8%|█▉                       | 78/1012 [01:59<17:49,  1.14s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 474.05it/s]
Season 2024-25:   8%|█▉                       | 79/1012 [02:01<21:03,  1.35s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 461.37it/s]
Season 2024-25:   8%|█▉                       | 80/1012 [02:02<20:21,  1.31s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 467.09it/s]
Season 2024-25:   8%|██                       | 81/1012 [02:03<19:40,  1.27s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 454.95it/s]
Season 2024-25:   8%|██                       | 82/1012 [02:06<26:01,  1.68s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 475.47it/s]
Season 2024-25:   8%|██                       | 83/1012 [02:07<24:02,  1.55s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 436.81it/s]
Season 2024-25:   8%|██                       | 84/1012 [02:09<26:36,  1.72s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 492.66it/s]
Season 2024-25:   8%|██                       | 85/1012 [02:10<22:00,  1.43s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 438.17it/s]
Season 2024-25:   8%|██                       | 86/1012 [02:11<21:48,  1.41s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 478.43it/s]
Season 2024-25:   9%|██▏                      | 87/1012 [02:12<17:07,  1.11s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 478.23it/s]
Season 2024-25:   9%|██▏                      | 88/1012 [02:14<20:58,  1.36s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 442.09it/s]
Season 2024-25:   9%|██▏                      | 89/1012 [02:15<21:55,  1.42s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 443.84it/s]
Season 2024-25:   9%|██▏                      | 90/1012 [02:19<34:28,  2.24s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 806.22it/s]
Season 2024-25:   9%|██▏                      | 91/1012 [02:25<47:56,  3.12s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 799.74it/s]
Season 2024-25:   9%|██▎                      | 92/1012 [02:25<35:54,  2.34s/it]
100%|██████████████████████████████████████████| 42/42 [00:00<00:00, 831.03it/s]
Season 2024-25:   9%|██▎                      | 93/1012 [02:26<27:33,  1.80s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 445.96it/s]
Season 2024-25:   9%|██▎                      | 94/1012 [02:26<21:43,  1.42s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 402.14it/s]
Season 2024-25:   9%|██▎                      | 95/1012 [02:27<17:37,  1.15s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 443.17it/s]
Season 2024-25:   9%|██▎                      | 96/1012 [02:28<17:13,  1.13s/it]
100%|██████████████████████████████████████████| 42/42 [00:00<00:00, 497.20it/s]
Season 2024-25:  10%|██▍                      | 97/1012 [02:30<20:28,  1.34s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 456.26it/s]
Season 2024-25:  10%|██▍                      | 98/1012 [02:30<16:27,  1.08s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 449.06it/s]
Season 2024-25:  10%|██▍                      | 99/1012 [02:35<34:44,  2.28s/it]
  0%|                                                    | 0/44 [00:00<?, ?it/s]
100%|██████████████████████████████████████████| 44/44 [00:00<00:00, 409.90it/s]
Season 2024-25:  10%|██▎                     | 100/1012 [02:37<32:02,  2.11s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 390.80it/s]
Season 2024-25:  10%|██▍                     | 101/1012 [02:37<24:35,  1.62s/it]
100%|██████████████████████████████████████████| 34/34 [00:00<00:00, 878.23it/s]
Season 2024-25:  10%|██▍                     | 102/1012 [02:41<33:26,  2.21s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 469.77it/s]
Season 2024-25:  10%|██▍                     | 103/1012 [02:42<26:22,  1.74s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 862.94it/s]

  0%|                                                    | 0/35 [00:00<?, ?it/s]

100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 436.61it/s]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 513.56it/s]

100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 451.31it/s]
Season 2024-25:  11%|██▌                     | 107/1012 [02:47<24:36,  1.63s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 470.56it/s]
Season 2024-25:  11%|██▌                     | 108/1012 [02:48<23:04,  1.53s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 494.21it/s]
Season 2024-25:  11%|██▌                     | 109/1012 [02:51<25:45,  1.71s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 411.10it/s]
Season 2024-25:  11%|██▌                     | 110/1012 [02:52<24:13,  1.61s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 587.31it/s]
Season 2024-25:  11%|██▋                     | 112/1012 [02:53<16:17,  1.09s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 438.08it/s]
Season 2024-25:  11%|██▋                     | 113/1012 [02:54<15:48,  1.06s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 432.92it/s]
Season 2024-25:  11%|██▋                     | 114/1012 [02:54<13:28,  1.11it/s]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 428.52it/s]
Season 2024-25:  11%|██▋                     | 115/1012 [02:57<22:45,  1.52s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 435.58it/s]
Season 2024-25:  11%|██▊                     | 116/1012 [03:01<30:17,  2.03s/it]
100%|██████████████████████████████████████████| 37/37 [00:00<00:00, 596.55it/s]
Season 2024-25:  12%|██▊                     | 117/1012 [03:01<24:08,  1.62s/it]
100%|██████████████████████████████████████████| 21/21 [00:00<00:00, 657.35it/s]
Season 2024-25:  12%|██▊                     | 118/1012 [03:02<19:56,  1.34s/it]
100%|██████████████████████████████████████████| 31/31 [00:00<00:00, 425.51it/s]
Season 2024-25:  12%|██▊                     | 119/1012 [03:02<16:19,  1.10s/it]
100%|██████████████████████████████████████████| 33/33 [00:00<00:00, 553.79it/s]
Season 2024-25:  12%|██▊                     | 120/1012 [03:04<16:22,  1.10s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 444.14it/s]
Season 2024-25:  12%|██▊                     | 121/1012 [03:04<14:05,  1.05it/s]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 450.75it/s]
Season 2024-25:  12%|██▉                     | 122/1012 [03:06<17:06,  1.15s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 439.29it/s]
Season 2024-25:  12%|██▉                     | 123/1012 [03:08<19:59,  1.35s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 524.38it/s]
Season 2024-25:  12%|██▉                     | 124/1012 [03:10<26:41,  1.80s/it]
100%|██████████████████████████████████████████| 32/32 [00:00<00:00, 843.57it/s]

100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 401.22it/s]
Season 2024-25:  12%|██▉                     | 126/1012 [03:11<17:28,  1.18s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 545.14it/s]
Season 2024-25:  13%|███                     | 127/1012 [03:12<14:06,  1.05it/s]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 435.38it/s]
Season 2024-25:  13%|███                     | 128/1012 [03:14<17:47,  1.21s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 645.07it/s]
Season 2024-25:  13%|███                     | 129/1012 [03:14<13:28,  1.09it/s]
100%|██████████████████████████████████████████| 22/22 [00:00<00:00, 458.69it/s]
Season 2024-25:  13%|███                     | 130/1012 [03:16<20:32,  1.40s/it]
100%|██████████████████████████████████████████| 29/29 [00:00<00:00, 457.37it/s]
Season 2024-25:  13%|███                     | 131/1012 [03:19<24:53,  1.70s/it]
100%|██████████████████████████████████████████| 36/36 [00:00<00:00, 502.84it/s]
Season 2024-25:  13%|███▏                    | 132/1012 [03:20<22:41,  1.55s/it]
100%|██████████████████████████████████████████| 30/30 [00:00<00:00, 447.80it/s]
Season 2024-25:  13%|███▏                    | 133/1012 [03:22<24:59,  1.71s/it]
100%|██████████████████████████████████████████| 26/26 [00:00<00:00, 409.44it/s]
Season 2024-25:  13%|███▏                    | 134/1012 [03:24<26:54,  1.84s/it]
100%|██████████████████████████████████████████| 38/38 [00:00<00:00, 509.03it/s]
Season 2024-25:  13%|███▏                    | 135/1012 [03:25<20:27,  1.40s/it]
100%|██████████████████████████████████████████| 16/16 [00:00<00:00, 368.56it/s]
Season 2024-25:  14%|███▏                    | 137/1012 [03:29<27:48,  1.91s/it]
100%|██████████████████████████████████████████| 27/27 [00:00<00:00, 794.30it/s]
Season 2024-25:  14%|███▎                    | 138/1012 [03:29<22:18,  1.53s/it]
100%|██████████████████████████████████████████| 35/35 [00:00<00:00, 460.14it/s]
Season 2024-25:  14%|███▎                    | 139/1012 [03:31<20:14,  1.39s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 420.10it/s]
Season 2024-25:  14%|███▎                    | 140/1012 [03:33<25:01,  1.72s/it]
100%|██████████████████████████████████████████| 28/28 [00:00<00:00, 429.08it/s]

[WARN] 83 games failed in 2024-25. Examples:
  - 0022400223: index 0 is out of bounds for axis 0 with size 0
  - 0022400390: index 0 is out of bounds for axis 0 with size 0
  - 0022400290: index 0 is out of bounds for axis 0 with size 0
  - 0022400209: index 0 is out of bounds for axis 0 with size 0
  - 0022401011: index 0 is out of bounds for axis 0 with size 0

## Save any New Failed Games into a new .pkl File

In [81]:
#Save any failed games to a .pkl file
import pickle
from datetime import datetime

with open(f"failed_games_{datetime.now().date()}.pkl", "wb") as file:
    pickle.dump(new_failed_games, file)

## Save the Results of failed_games_df into a .CSV

In [83]:
from datetime import datetime

failed_games_df.to_csv(f"stint_wise_data_from_failed_games_{datetime.now().date()}.csv", index = False)